// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "guess_babay.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic guess_babay::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic guess_babay::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<29> guess_babay::ap_ST_fsm_state1 = "1";
const sc_lv<29> guess_babay::ap_ST_fsm_state2 = "10";
const sc_lv<29> guess_babay::ap_ST_fsm_state3 = "100";
const sc_lv<29> guess_babay::ap_ST_fsm_state4 = "1000";
const sc_lv<29> guess_babay::ap_ST_fsm_state5 = "10000";
const sc_lv<29> guess_babay::ap_ST_fsm_state6 = "100000";
const sc_lv<29> guess_babay::ap_ST_fsm_state7 = "1000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state8 = "10000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state9 = "100000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state10 = "1000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state11 = "10000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state12 = "100000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<29> guess_babay::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<32> guess_babay::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> guess_babay::ap_const_lv32_5 = "101";
const sc_lv<32> guess_babay::ap_const_lv32_E = "1110";
const sc_lv<1> guess_babay::ap_const_lv1_0 = "0";
const sc_lv<32> guess_babay::ap_const_lv32_18 = "11000";
const sc_lv<32> guess_babay::ap_const_lv32_9 = "1001";
const sc_lv<32> guess_babay::ap_const_lv32_16 = "10110";
const sc_lv<32> guess_babay::ap_const_lv32_1 = "1";
const sc_lv<32> guess_babay::ap_const_lv32_2 = "10";
const sc_lv<32> guess_babay::ap_const_lv32_3 = "11";
const sc_lv<32> guess_babay::ap_const_lv32_4 = "100";
const sc_lv<32> guess_babay::ap_const_lv32_A = "1010";
const sc_lv<32> guess_babay::ap_const_lv32_B = "1011";
const sc_lv<1> guess_babay::ap_const_lv1_1 = "1";
const sc_lv<32> guess_babay::ap_const_lv32_C = "1100";
const sc_lv<32> guess_babay::ap_const_lv32_12 = "10010";
const sc_lv<32> guess_babay::ap_const_lv32_13 = "10011";
const sc_lv<32> guess_babay::ap_const_lv32_1C = "11100";
const sc_lv<4> guess_babay::ap_const_lv4_0 = "0000";
const sc_lv<32> guess_babay::ap_const_lv32_BF800000 = "10111111100000000000000000000000";
const sc_lv<32> guess_babay::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<32> guess_babay::ap_const_lv32_6 = "110";
const sc_lv<32> guess_babay::ap_const_lv32_F = "1111";
const sc_lv<32> guess_babay::ap_const_lv32_19 = "11001";
const sc_lv<32> guess_babay::ap_const_lv32_D = "1101";
const sc_lv<32> guess_babay::ap_const_lv32_17 = "10111";
const sc_lv<32> guess_babay::ap_const_lv32_3F000000 = "111111000000000000000000000000";
const sc_lv<32> guess_babay::ap_const_lv32_BF000000 = "10111111000000000000000000000000";
const sc_lv<4> guess_babay::ap_const_lv4_C = "1100";
const sc_lv<4> guess_babay::ap_const_lv4_1 = "1";
const sc_lv<2> guess_babay::ap_const_lv2_0 = "00";
const sc_lv<32> guess_babay::ap_const_lv32_1E = "11110";
const sc_lv<8> guess_babay::ap_const_lv8_FF = "11111111";
const sc_lv<23> guess_babay::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> guess_babay::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<4> guess_babay::ap_const_lv4_D = "1101";
const sc_lv<2> guess_babay::ap_const_lv2_1 = "1";
const sc_lv<5> guess_babay::ap_const_lv5_3 = "11";
const sc_lv<5> guess_babay::ap_const_lv5_4 = "100";
const bool guess_babay::ap_const_boolean_1 = true;

guess_babay::guess_babay(sc_module_name name) : sc_module(name), mVcdFile(0) {
    U_babay_U = new guess_edu_u_educaibs("U_babay_U");
    U_babay_U->clk(ap_clk);
    U_babay_U->reset(ap_rst);
    U_babay_U->address0(U_babay_address0);
    U_babay_U->ce0(U_babay_ce0);
    U_babay_U->we0(U_babay_we0);
    U_babay_U->d0(U_babay_d0);
    U_babay_U->q0(U_babay_q0);
    predictive_controbkb_U36 = new predictive_controbkb<1,4,32,32,32>("predictive_controbkb_U36");
    predictive_controbkb_U36->clk(ap_clk);
    predictive_controbkb_U36->reset(ap_rst);
    predictive_controbkb_U36->din0(grp_fu_227_p0);
    predictive_controbkb_U36->din1(grp_fu_227_p1);
    predictive_controbkb_U36->opcode(grp_fu_227_opcode);
    predictive_controbkb_U36->ce(ap_var_for_const0);
    predictive_controbkb_U36->dout(grp_fu_227_p2);
    predictive_controcud_U37 = new predictive_controcud<1,2,32,32,32>("predictive_controcud_U37");
    predictive_controcud_U37->clk(ap_clk);
    predictive_controcud_U37->reset(ap_rst);
    predictive_controcud_U37->din0(grp_fu_237_p0);
    predictive_controcud_U37->din1(grp_fu_237_p1);
    predictive_controcud_U37->ce(ap_var_for_const0);
    predictive_controcud_U37->dout(grp_fu_237_p2);
    predictive_controjbC_U38 = new predictive_controjbC<1,1,32,32,1>("predictive_controjbC_U38");
    predictive_controjbC_U38->din0(tmp_83_reg_157);
    predictive_controjbC_U38->din1(ap_var_for_const1);
    predictive_controjbC_U38->opcode(ap_var_for_const2);
    predictive_controjbC_U38->dout(tmp_102_fu_241_p2);
    predictive_controjbC_U39 = new predictive_controjbC<1,1,32,32,1>("predictive_controjbC_U39");
    predictive_controjbC_U39->din0(tmp_83_reg_157);
    predictive_controjbC_U39->din1(ap_var_for_const1);
    predictive_controjbC_U39->opcode(ap_var_for_const3);
    predictive_controjbC_U39->dout(tmp_104_fu_247_p2);
    predictive_controjbC_U40 = new predictive_controjbC<1,1,32,32,1>("predictive_controjbC_U40");
    predictive_controjbC_U40->din0(tmp_83_reg_157);
    predictive_controjbC_U40->din1(ap_var_for_const4);
    predictive_controjbC_U40->opcode(ap_var_for_const2);
    predictive_controjbC_U40->dout(tmp_106_fu_253_p2);
    predictive_controjbC_U41 = new predictive_controjbC<1,1,32,32,1>("predictive_controjbC_U41");
    predictive_controjbC_U41->din0(tmp_83_reg_157);
    predictive_controjbC_U41->din1(ap_var_for_const4);
    predictive_controjbC_U41->opcode(ap_var_for_const3);
    predictive_controjbC_U41->dout(tmp_107_fu_259_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_H_Hat_Inv_a_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_86_fu_349_p1 );

    SC_METHOD(thread_H_Hat_Inv_a_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_U_babay_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( U_babay_addr_reg_536 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_fu_289_p1 );
    sensitive << ( tmp_97_fu_511_p1 );
    sensitive << ( tmp_103_fu_395_p2 );
    sensitive << ( tmp_93_fu_407_p2 );
    sensitive << ( tmp_108_fu_413_p2 );

    SC_METHOD(thread_U_babay_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_103_fu_395_p2 );
    sensitive << ( tmp_93_fu_407_p2 );
    sensitive << ( tmp_108_fu_413_p2 );

    SC_METHOD(thread_U_babay_d0);
    sensitive << ( grp_fu_227_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( tmp_103_fu_395_p2 );
    sensitive << ( tmp_93_fu_407_p2 );
    sensitive << ( tmp_108_fu_413_p2 );

    SC_METHOD(thread_U_babay_we0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_277_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( tmp_103_fu_395_p2 );
    sensitive << ( tmp_93_fu_407_p2 );
    sensitive << ( tmp_108_fu_413_p2 );

    SC_METHOD(thread_U_unc_kk_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_91_fu_516_p1 );

    SC_METHOD(thread_U_unc_kk_ce0);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_V_Gen_a_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_96_fu_506_p1 );

    SC_METHOD(thread_V_Gen_a_ce0);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_fu_433_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_fu_433_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_fu_433_p2 );
    sensitive << ( babay_rho_reg_180 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_col2_cast2_fu_475_p1);
    sensitive << ( col2_reg_216 );

    SC_METHOD(thread_col_5_fu_334_p2);
    sensitive << ( col_reg_169 );

    SC_METHOD(thread_col_6_fu_485_p2);
    sensitive << ( col2_reg_216 );

    SC_METHOD(thread_col_cast7_fu_324_p1);
    sensitive << ( col_reg_169 );

    SC_METHOD(thread_exitcond1_fu_433_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( row1_reg_192 );

    SC_METHOD(thread_exitcond2_fu_328_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_reg_169 );

    SC_METHOD(thread_exitcond3_fu_277_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_146 );

    SC_METHOD(thread_exitcond_fu_479_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( col2_reg_216 );

    SC_METHOD(thread_grp_fu_227_opcode);
    sensitive << ( tmp_94_reg_609 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_fu_227_p0);
    sensitive << ( U_unc_kk_q0 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_83_reg_157 );
    sensitive << ( babay_rho_reg_180 );
    sensitive << ( temp_value_reg_204 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_fu_227_p1);
    sensitive << ( reg_265 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( temp_value_reg_204 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_fu_237_p0);
    sensitive << ( reg_270 );
    sensitive << ( tmp_87_fu_429_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( V_Gen_a_load_reg_629 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_237_p1);
    sensitive << ( reg_270 );
    sensitive << ( theta_kk_load_reg_578 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( U_babay_load_reg_634 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_notlhs_fu_377_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( tmp_99_fu_363_p4 );

    SC_METHOD(thread_notrhs_fu_383_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( tmp_100_fu_373_p1 );

    SC_METHOD(thread_p_shl6_cast_fu_314_p1);
    sensitive << ( p_shl6_fu_306_p3 );

    SC_METHOD(thread_p_shl6_fu_306_p3);
    sensitive << ( row_reg_146 );

    SC_METHOD(thread_p_shl7_cast_fu_453_p1);
    sensitive << ( p_shl7_fu_445_p3 );

    SC_METHOD(thread_p_shl7_fu_445_p3);
    sensitive << ( row1_reg_192 );

    SC_METHOD(thread_p_shl8_cast_fu_465_p1);
    sensitive << ( p_shl8_fu_457_p3 );

    SC_METHOD(thread_p_shl8_fu_457_p3);
    sensitive << ( row1_reg_192 );

    SC_METHOD(thread_p_shl_cast_fu_302_p1);
    sensitive << ( p_shl_fu_294_p3 );

    SC_METHOD(thread_p_shl_fu_294_p3);
    sensitive << ( row_reg_146 );

    SC_METHOD(thread_row_15_fu_283_p2);
    sensitive << ( row_reg_146 );

    SC_METHOD(thread_row_1_fu_439_p2);
    sensitive << ( row1_reg_192 );

    SC_METHOD(thread_temp_value_1_fu_521_p3);
    sensitive << ( tmp_94_reg_609 );
    sensitive << ( grp_fu_227_p2 );
    sensitive << ( temp_value_reg_204 );

    SC_METHOD(thread_theta_kk_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_88_fu_354_p1 );

    SC_METHOD(thread_theta_kk_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_100_fu_373_p1);
    sensitive << ( tmp_83_to_int_fu_359_p1 );

    SC_METHOD(thread_tmp_101_fu_389_p2);
    sensitive << ( notrhs_fu_383_p2 );
    sensitive << ( notlhs_fu_377_p2 );

    SC_METHOD(thread_tmp_103_fu_395_p2);
    sensitive << ( tmp_101_fu_389_p2 );
    sensitive << ( tmp_102_fu_241_p2 );

    SC_METHOD(thread_tmp_105_fu_401_p2);
    sensitive << ( tmp_101_fu_389_p2 );
    sensitive << ( tmp_104_fu_247_p2 );

    SC_METHOD(thread_tmp_108_fu_413_p2);
    sensitive << ( tmp_101_fu_389_p2 );
    sensitive << ( tmp_107_fu_259_p2 );

    SC_METHOD(thread_tmp_82_fu_469_p2);
    sensitive << ( p_shl7_cast_fu_453_p1 );
    sensitive << ( p_shl8_cast_fu_465_p1 );

    SC_METHOD(thread_tmp_83_to_int_fu_359_p1);
    sensitive << ( tmp_83_reg_157 );

    SC_METHOD(thread_tmp_85_cast_fu_345_p1);
    sensitive << ( tmp_85_fu_340_p2 );

    SC_METHOD(thread_tmp_85_fu_340_p2);
    sensitive << ( tmp_s_reg_541 );
    sensitive << ( col_cast7_fu_324_p1 );

    SC_METHOD(thread_tmp_86_fu_349_p1);
    sensitive << ( tmp_85_cast_fu_345_p1 );

    SC_METHOD(thread_tmp_87_fu_429_p1);
    sensitive << ( tmp_88_neg_reg_573 );

    SC_METHOD(thread_tmp_88_fu_354_p1);
    sensitive << ( col_reg_169 );

    SC_METHOD(thread_tmp_88_neg_fu_423_p2);
    sensitive << ( tmp_88_to_int_fu_419_p1 );

    SC_METHOD(thread_tmp_88_to_int_fu_419_p1);
    sensitive << ( H_Hat_Inv_a_q0 );

    SC_METHOD(thread_tmp_91_fu_516_p1);
    sensitive << ( row1_reg_192 );

    SC_METHOD(thread_tmp_93_fu_407_p2);
    sensitive << ( tmp_105_fu_401_p2 );
    sensitive << ( tmp_106_fu_253_p2 );

    SC_METHOD(thread_tmp_94_fu_491_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_fu_479_p2 );
    sensitive << ( row1_reg_192 );
    sensitive << ( col2_reg_216 );

    SC_METHOD(thread_tmp_95_fu_497_p2);
    sensitive << ( tmp_82_reg_596 );
    sensitive << ( col2_cast2_fu_475_p1 );

    SC_METHOD(thread_tmp_96_cast_fu_502_p1);
    sensitive << ( tmp_95_fu_497_p2 );

    SC_METHOD(thread_tmp_96_fu_506_p1);
    sensitive << ( tmp_96_cast_fu_502_p1 );

    SC_METHOD(thread_tmp_97_fu_511_p1);
    sensitive << ( col2_reg_216 );

    SC_METHOD(thread_tmp_99_fu_363_p4);
    sensitive << ( tmp_83_to_int_fu_359_p1 );

    SC_METHOD(thread_tmp_fu_289_p1);
    sensitive << ( row_reg_146 );

    SC_METHOD(thread_tmp_s_fu_318_p2);
    sensitive << ( p_shl_cast_fu_302_p1 );
    sensitive << ( p_shl6_cast_fu_314_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_277_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond1_fu_433_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_fu_479_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    ap_CS_fsm = "00000000000000000000000000001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "guess_babay_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, V_Gen_a_address0, "(port)V_Gen_a_address0");
    sc_trace(mVcdFile, V_Gen_a_ce0, "(port)V_Gen_a_ce0");
    sc_trace(mVcdFile, V_Gen_a_q0, "(port)V_Gen_a_q0");
    sc_trace(mVcdFile, H_Hat_Inv_a_address0, "(port)H_Hat_Inv_a_address0");
    sc_trace(mVcdFile, H_Hat_Inv_a_ce0, "(port)H_Hat_Inv_a_ce0");
    sc_trace(mVcdFile, H_Hat_Inv_a_q0, "(port)H_Hat_Inv_a_q0");
    sc_trace(mVcdFile, U_unc_kk_address0, "(port)U_unc_kk_address0");
    sc_trace(mVcdFile, U_unc_kk_ce0, "(port)U_unc_kk_ce0");
    sc_trace(mVcdFile, U_unc_kk_q0, "(port)U_unc_kk_q0");
    sc_trace(mVcdFile, theta_kk_address0, "(port)theta_kk_address0");
    sc_trace(mVcdFile, theta_kk_ce0, "(port)theta_kk_ce0");
    sc_trace(mVcdFile, theta_kk_q0, "(port)theta_kk_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_237_p2, "grp_fu_237_p2");
    sc_trace(mVcdFile, reg_265, "reg_265");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_94_reg_609, "tmp_94_reg_609");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, grp_fu_227_p2, "grp_fu_227_p2");
    sc_trace(mVcdFile, reg_270, "reg_270");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, row_15_fu_283_p2, "row_15_fu_283_p2");
    sc_trace(mVcdFile, row_15_reg_531, "row_15_reg_531");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, U_babay_addr_reg_536, "U_babay_addr_reg_536");
    sc_trace(mVcdFile, exitcond3_fu_277_p2, "exitcond3_fu_277_p2");
    sc_trace(mVcdFile, tmp_s_fu_318_p2, "tmp_s_fu_318_p2");
    sc_trace(mVcdFile, tmp_s_reg_541, "tmp_s_reg_541");
    sc_trace(mVcdFile, col_5_fu_334_p2, "col_5_fu_334_p2");
    sc_trace(mVcdFile, col_5_reg_549, "col_5_reg_549");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond2_fu_328_p2, "exitcond2_fu_328_p2");
    sc_trace(mVcdFile, tmp_88_neg_fu_423_p2, "tmp_88_neg_fu_423_p2");
    sc_trace(mVcdFile, tmp_88_neg_reg_573, "tmp_88_neg_reg_573");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, theta_kk_load_reg_578, "theta_kk_load_reg_578");
    sc_trace(mVcdFile, tmp_87_fu_429_p1, "tmp_87_fu_429_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, row_1_fu_439_p2, "row_1_fu_439_p2");
    sc_trace(mVcdFile, row_1_reg_591, "row_1_reg_591");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_82_fu_469_p2, "tmp_82_fu_469_p2");
    sc_trace(mVcdFile, tmp_82_reg_596, "tmp_82_reg_596");
    sc_trace(mVcdFile, exitcond1_fu_433_p2, "exitcond1_fu_433_p2");
    sc_trace(mVcdFile, col_6_fu_485_p2, "col_6_fu_485_p2");
    sc_trace(mVcdFile, col_6_reg_604, "col_6_reg_604");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_94_fu_491_p2, "tmp_94_fu_491_p2");
    sc_trace(mVcdFile, exitcond_fu_479_p2, "exitcond_fu_479_p2");
    sc_trace(mVcdFile, V_Gen_a_load_reg_629, "V_Gen_a_load_reg_629");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, U_babay_q0, "U_babay_q0");
    sc_trace(mVcdFile, U_babay_load_reg_634, "U_babay_load_reg_634");
    sc_trace(mVcdFile, temp_value_1_fu_521_p3, "temp_value_1_fu_521_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, U_babay_address0, "U_babay_address0");
    sc_trace(mVcdFile, U_babay_ce0, "U_babay_ce0");
    sc_trace(mVcdFile, U_babay_we0, "U_babay_we0");
    sc_trace(mVcdFile, U_babay_d0, "U_babay_d0");
    sc_trace(mVcdFile, row_reg_146, "row_reg_146");
    sc_trace(mVcdFile, tmp_83_reg_157, "tmp_83_reg_157");
    sc_trace(mVcdFile, col_reg_169, "col_reg_169");
    sc_trace(mVcdFile, babay_rho_reg_180, "babay_rho_reg_180");
    sc_trace(mVcdFile, row1_reg_192, "row1_reg_192");
    sc_trace(mVcdFile, temp_value_reg_204, "temp_value_reg_204");
    sc_trace(mVcdFile, col2_reg_216, "col2_reg_216");
    sc_trace(mVcdFile, tmp_fu_289_p1, "tmp_fu_289_p1");
    sc_trace(mVcdFile, tmp_86_fu_349_p1, "tmp_86_fu_349_p1");
    sc_trace(mVcdFile, tmp_88_fu_354_p1, "tmp_88_fu_354_p1");
    sc_trace(mVcdFile, tmp_96_fu_506_p1, "tmp_96_fu_506_p1");
    sc_trace(mVcdFile, tmp_97_fu_511_p1, "tmp_97_fu_511_p1");
    sc_trace(mVcdFile, tmp_91_fu_516_p1, "tmp_91_fu_516_p1");
    sc_trace(mVcdFile, tmp_103_fu_395_p2, "tmp_103_fu_395_p2");
    sc_trace(mVcdFile, tmp_93_fu_407_p2, "tmp_93_fu_407_p2");
    sc_trace(mVcdFile, tmp_108_fu_413_p2, "tmp_108_fu_413_p2");
    sc_trace(mVcdFile, grp_fu_227_p0, "grp_fu_227_p0");
    sc_trace(mVcdFile, grp_fu_227_p1, "grp_fu_227_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, grp_fu_237_p0, "grp_fu_237_p0");
    sc_trace(mVcdFile, grp_fu_237_p1, "grp_fu_237_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, p_shl_fu_294_p3, "p_shl_fu_294_p3");
    sc_trace(mVcdFile, p_shl6_fu_306_p3, "p_shl6_fu_306_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_302_p1, "p_shl_cast_fu_302_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_314_p1, "p_shl6_cast_fu_314_p1");
    sc_trace(mVcdFile, col_cast7_fu_324_p1, "col_cast7_fu_324_p1");
    sc_trace(mVcdFile, tmp_85_fu_340_p2, "tmp_85_fu_340_p2");
    sc_trace(mVcdFile, tmp_85_cast_fu_345_p1, "tmp_85_cast_fu_345_p1");
    sc_trace(mVcdFile, tmp_83_to_int_fu_359_p1, "tmp_83_to_int_fu_359_p1");
    sc_trace(mVcdFile, tmp_99_fu_363_p4, "tmp_99_fu_363_p4");
    sc_trace(mVcdFile, tmp_100_fu_373_p1, "tmp_100_fu_373_p1");
    sc_trace(mVcdFile, notrhs_fu_383_p2, "notrhs_fu_383_p2");
    sc_trace(mVcdFile, notlhs_fu_377_p2, "notlhs_fu_377_p2");
    sc_trace(mVcdFile, tmp_101_fu_389_p2, "tmp_101_fu_389_p2");
    sc_trace(mVcdFile, tmp_102_fu_241_p2, "tmp_102_fu_241_p2");
    sc_trace(mVcdFile, tmp_104_fu_247_p2, "tmp_104_fu_247_p2");
    sc_trace(mVcdFile, tmp_105_fu_401_p2, "tmp_105_fu_401_p2");
    sc_trace(mVcdFile, tmp_106_fu_253_p2, "tmp_106_fu_253_p2");
    sc_trace(mVcdFile, tmp_107_fu_259_p2, "tmp_107_fu_259_p2");
    sc_trace(mVcdFile, tmp_88_to_int_fu_419_p1, "tmp_88_to_int_fu_419_p1");
    sc_trace(mVcdFile, p_shl7_fu_445_p3, "p_shl7_fu_445_p3");
    sc_trace(mVcdFile, p_shl8_fu_457_p3, "p_shl8_fu_457_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_453_p1, "p_shl7_cast_fu_453_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_465_p1, "p_shl8_cast_fu_465_p1");
    sc_trace(mVcdFile, col2_cast2_fu_475_p1, "col2_cast2_fu_475_p1");
    sc_trace(mVcdFile, tmp_95_fu_497_p2, "tmp_95_fu_497_p2");
    sc_trace(mVcdFile, tmp_96_cast_fu_502_p1, "tmp_96_cast_fu_502_p1");
    sc_trace(mVcdFile, grp_fu_227_opcode, "grp_fu_227_opcode");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

guess_babay::~guess_babay() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete U_babay_U;
    delete predictive_controbkb_U36;
    delete predictive_controcud_U37;
    delete predictive_controjbC_U38;
    delete predictive_controjbC_U39;
    delete predictive_controjbC_U40;
    delete predictive_controjbC_U41;
}

void guess_babay::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void guess_babay::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_3F000000;
}

void guess_babay::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv32_BF000000;
}

void guess_babay::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_3;
}

void guess_babay::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv5_4;
}

void guess_babay::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
             esl_seteq<1,1,1>(exitcond1_fu_433_p2.read(), ap_const_lv1_1))) {
            ap_return_preg = babay_rho_reg_180.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_277_p2.read(), ap_const_lv1_1))) {
        babay_rho_reg_180 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        babay_rho_reg_180 = grp_fu_227_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        col2_reg_216 = col_6_reg_604.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_433_p2.read()))) {
        col2_reg_216 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        col_reg_169 = col_5_reg_549.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_277_p2.read()))) {
        col_reg_169 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_277_p2.read(), ap_const_lv1_1))) {
        row1_reg_192 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        row1_reg_192 = row_1_reg_591.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1))) {
        row_reg_146 = row_15_reg_531.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        row_reg_146 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        temp_value_reg_204 = temp_value_1_fu_521_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_433_p2.read()))) {
        temp_value_reg_204 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_83_reg_157 = grp_fu_227_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_277_p2.read()))) {
        tmp_83_reg_157 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_277_p2.read()))) {
        U_babay_addr_reg_536 =  (sc_lv<4>) (tmp_fu_289_p1.read());
        tmp_s_reg_541 = tmp_s_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        U_babay_load_reg_634 = U_babay_q0.read();
        V_Gen_a_load_reg_629 = V_Gen_a_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        col_5_reg_549 = col_5_fu_334_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        col_6_reg_604 = col_6_fu_485_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
  esl_seteq<1,1,1>(tmp_94_reg_609.read(), ap_const_lv1_0)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        reg_265 = grp_fu_237_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        reg_270 = grp_fu_227_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_15_reg_531 = row_15_fu_283_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        row_1_reg_591 = row_1_fu_439_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        theta_kk_load_reg_578 = theta_kk_q0.read();
        tmp_88_neg_reg_573 = tmp_88_neg_fu_423_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_433_p2.read()))) {
        tmp_82_reg_596 = tmp_82_fu_469_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_479_p2.read()))) {
        tmp_94_reg_609 = tmp_94_fu_491_p2.read();
    }
}

void guess_babay::thread_H_Hat_Inv_a_address0() {
    H_Hat_Inv_a_address0 =  (sc_lv<8>) (tmp_86_fu_349_p1.read());
}

void guess_babay::thread_H_Hat_Inv_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        H_Hat_Inv_a_ce0 = ap_const_logic_1;
    } else {
        H_Hat_Inv_a_ce0 = ap_const_logic_0;
    }
}

void guess_babay::thread_U_babay_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        U_babay_address0 =  (sc_lv<4>) (tmp_97_fu_511_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_93_fu_407_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_108_fu_413_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_93_fu_407_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_103_fu_395_p2.read())))) {
        U_babay_address0 = U_babay_addr_reg_536.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        U_babay_address0 =  (sc_lv<4>) (tmp_fu_289_p1.read());
    } else {
        U_babay_address0 = "XXXX";
    }
}

void guess_babay::thread_U_babay_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_93_fu_407_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_108_fu_413_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_93_fu_407_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_103_fu_395_p2.read())))) {
        U_babay_ce0 = ap_const_logic_1;
    } else {
        U_babay_ce0 = ap_const_logic_0;
    }
}

void guess_babay::thread_U_babay_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        U_babay_d0 = grp_fu_227_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_103_fu_395_p2.read()))) {
        U_babay_d0 = ap_const_lv32_3F800000;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_93_fu_407_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_108_fu_413_p2.read()))) {
        U_babay_d0 = ap_const_lv32_BF800000;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_93_fu_407_p2.read())))) {
        U_babay_d0 = ap_const_lv32_0;
    } else {
        U_babay_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_babay::thread_U_babay_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_277_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_93_fu_407_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_108_fu_413_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_103_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_93_fu_407_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_103_fu_395_p2.read())))) {
        U_babay_we0 = ap_const_logic_1;
    } else {
        U_babay_we0 = ap_const_logic_0;
    }
}

void guess_babay::thread_U_unc_kk_address0() {
    U_unc_kk_address0 =  (sc_lv<4>) (tmp_91_fu_516_p1.read());
}

void guess_babay::thread_U_unc_kk_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        U_unc_kk_ce0 = ap_const_logic_1;
    } else {
        U_unc_kk_ce0 = ap_const_logic_0;
    }
}

void guess_babay::thread_V_Gen_a_address0() {
    V_Gen_a_address0 =  (sc_lv<8>) (tmp_96_fu_506_p1.read());
}

void guess_babay::thread_V_Gen_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        V_Gen_a_ce0 = ap_const_logic_1;
    } else {
        V_Gen_a_ce0 = ap_const_logic_0;
    }
}

void guess_babay::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void guess_babay::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void guess_babay::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void guess_babay::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void guess_babay::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void guess_babay::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void guess_babay::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void guess_babay::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void guess_babay::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void guess_babay::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void guess_babay::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void guess_babay::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void guess_babay::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void guess_babay::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void guess_babay::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void guess_babay::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void guess_babay::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void guess_babay::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void guess_babay::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void guess_babay::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void guess_babay::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void guess_babay::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_433_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void guess_babay::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void guess_babay::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_433_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void guess_babay::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_433_p2.read(), ap_const_lv1_1))) {
        ap_return = babay_rho_reg_180.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void guess_babay::thread_col2_cast2_fu_475_p1() {
    col2_cast2_fu_475_p1 = esl_zext<9,4>(col2_reg_216.read());
}

void guess_babay::thread_col_5_fu_334_p2() {
    col_5_fu_334_p2 = (!col_reg_169.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_reg_169.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_babay::thread_col_6_fu_485_p2() {
    col_6_fu_485_p2 = (!col2_reg_216.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col2_reg_216.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_babay::thread_col_cast7_fu_324_p1() {
    col_cast7_fu_324_p1 = esl_zext<9,4>(col_reg_169.read());
}

void guess_babay::thread_exitcond1_fu_433_p2() {
    exitcond1_fu_433_p2 = (!row1_reg_192.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(row1_reg_192.read() == ap_const_lv4_C);
}

void guess_babay::thread_exitcond2_fu_328_p2() {
    exitcond2_fu_328_p2 = (!col_reg_169.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_169.read() == ap_const_lv4_C);
}

void guess_babay::thread_exitcond3_fu_277_p2() {
    exitcond3_fu_277_p2 = (!row_reg_146.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_146.read() == ap_const_lv4_C);
}

void guess_babay::thread_exitcond_fu_479_p2() {
    exitcond_fu_479_p2 = (!col2_reg_216.read().is_01() || !ap_const_lv4_D.is_01())? sc_lv<1>(): sc_lv<1>(col2_reg_216.read() == ap_const_lv4_D);
}

void guess_babay::thread_grp_fu_227_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_227_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || 
                (esl_seteq<1,1,1>(tmp_94_reg_609.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())))) {
        grp_fu_227_opcode = ap_const_lv2_0;
    } else {
        grp_fu_227_opcode =  (sc_lv<2>) ("XX");
    }
}

void guess_babay::thread_grp_fu_227_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        grp_fu_227_p0 = babay_rho_reg_180.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_227_p0 = U_unc_kk_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        grp_fu_227_p0 = temp_value_reg_204.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_227_p0 = tmp_83_reg_157.read();
    } else {
        grp_fu_227_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_babay::thread_grp_fu_227_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_227_p1 = temp_value_reg_204.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()))) {
        grp_fu_227_p1 = reg_265.read();
    } else {
        grp_fu_227_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_babay::thread_grp_fu_237_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_237_p0 = reg_270.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_237_p0 = V_Gen_a_load_reg_629.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_237_p0 = tmp_87_fu_429_p1.read();
    } else {
        grp_fu_237_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_babay::thread_grp_fu_237_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_237_p1 = reg_270.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_237_p1 = U_babay_load_reg_634.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_237_p1 = theta_kk_load_reg_578.read();
    } else {
        grp_fu_237_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_babay::thread_notlhs_fu_377_p2() {
    notlhs_fu_377_p2 = (!tmp_99_fu_363_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_99_fu_363_p4.read() != ap_const_lv8_FF);
}

void guess_babay::thread_notrhs_fu_383_p2() {
    notrhs_fu_383_p2 = (!tmp_100_fu_373_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_100_fu_373_p1.read() == ap_const_lv23_0);
}

void guess_babay::thread_p_shl6_cast_fu_314_p1() {
    p_shl6_cast_fu_314_p1 = esl_zext<9,6>(p_shl6_fu_306_p3.read());
}

void guess_babay::thread_p_shl6_fu_306_p3() {
    p_shl6_fu_306_p3 = esl_concat<4,2>(row_reg_146.read(), ap_const_lv2_0);
}

void guess_babay::thread_p_shl7_cast_fu_453_p1() {
    p_shl7_cast_fu_453_p1 = esl_zext<9,8>(p_shl7_fu_445_p3.read());
}

void guess_babay::thread_p_shl7_fu_445_p3() {
    p_shl7_fu_445_p3 = esl_concat<4,4>(row1_reg_192.read(), ap_const_lv4_0);
}

void guess_babay::thread_p_shl8_cast_fu_465_p1() {
    p_shl8_cast_fu_465_p1 = esl_zext<9,6>(p_shl8_fu_457_p3.read());
}

void guess_babay::thread_p_shl8_fu_457_p3() {
    p_shl8_fu_457_p3 = esl_concat<4,2>(row1_reg_192.read(), ap_const_lv2_0);
}

void guess_babay::thread_p_shl_cast_fu_302_p1() {
    p_shl_cast_fu_302_p1 = esl_zext<9,8>(p_shl_fu_294_p3.read());
}

void guess_babay::thread_p_shl_fu_294_p3() {
    p_shl_fu_294_p3 = esl_concat<4,4>(row_reg_146.read(), ap_const_lv4_0);
}

void guess_babay::thread_row_15_fu_283_p2() {
    row_15_fu_283_p2 = (!row_reg_146.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_reg_146.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_babay::thread_row_1_fu_439_p2() {
    row_1_fu_439_p2 = (!row1_reg_192.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row1_reg_192.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_babay::thread_temp_value_1_fu_521_p3() {
    temp_value_1_fu_521_p3 = (!tmp_94_reg_609.read()[0].is_01())? sc_lv<32>(): ((tmp_94_reg_609.read()[0].to_bool())? temp_value_reg_204.read(): grp_fu_227_p2.read());
}

void guess_babay::thread_theta_kk_address0() {
    theta_kk_address0 =  (sc_lv<4>) (tmp_88_fu_354_p1.read());
}

void guess_babay::thread_theta_kk_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        theta_kk_ce0 = ap_const_logic_1;
    } else {
        theta_kk_ce0 = ap_const_logic_0;
    }
}

void guess_babay::thread_tmp_100_fu_373_p1() {
    tmp_100_fu_373_p1 = tmp_83_to_int_fu_359_p1.read().range(23-1, 0);
}

void guess_babay::thread_tmp_101_fu_389_p2() {
    tmp_101_fu_389_p2 = (notrhs_fu_383_p2.read() | notlhs_fu_377_p2.read());
}

void guess_babay::thread_tmp_103_fu_395_p2() {
    tmp_103_fu_395_p2 = (tmp_101_fu_389_p2.read() & tmp_102_fu_241_p2.read());
}

void guess_babay::thread_tmp_105_fu_401_p2() {
    tmp_105_fu_401_p2 = (tmp_101_fu_389_p2.read() & tmp_104_fu_247_p2.read());
}

void guess_babay::thread_tmp_108_fu_413_p2() {
    tmp_108_fu_413_p2 = (tmp_101_fu_389_p2.read() & tmp_107_fu_259_p2.read());
}

void guess_babay::thread_tmp_82_fu_469_p2() {
    tmp_82_fu_469_p2 = (!p_shl7_cast_fu_453_p1.read().is_01() || !p_shl8_cast_fu_465_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl7_cast_fu_453_p1.read()) - sc_biguint<9>(p_shl8_cast_fu_465_p1.read()));
}

void guess_babay::thread_tmp_83_to_int_fu_359_p1() {
    tmp_83_to_int_fu_359_p1 = tmp_83_reg_157.read();
}

void guess_babay::thread_tmp_85_cast_fu_345_p1() {
    tmp_85_cast_fu_345_p1 = esl_sext<32,9>(tmp_85_fu_340_p2.read());
}

void guess_babay::thread_tmp_85_fu_340_p2() {
    tmp_85_fu_340_p2 = (!col_cast7_fu_324_p1.read().is_01() || !tmp_s_reg_541.read().is_01())? sc_lv<9>(): (sc_biguint<9>(col_cast7_fu_324_p1.read()) + sc_biguint<9>(tmp_s_reg_541.read()));
}

void guess_babay::thread_tmp_86_fu_349_p1() {
    tmp_86_fu_349_p1 = esl_zext<64,32>(tmp_85_cast_fu_345_p1.read());
}

void guess_babay::thread_tmp_87_fu_429_p1() {
    tmp_87_fu_429_p1 = tmp_88_neg_reg_573.read();
}

void guess_babay::thread_tmp_88_fu_354_p1() {
    tmp_88_fu_354_p1 = esl_zext<64,4>(col_reg_169.read());
}

void guess_babay::thread_tmp_88_neg_fu_423_p2() {
    tmp_88_neg_fu_423_p2 = (tmp_88_to_int_fu_419_p1.read() ^ ap_const_lv32_80000000);
}

void guess_babay::thread_tmp_88_to_int_fu_419_p1() {
    tmp_88_to_int_fu_419_p1 = H_Hat_Inv_a_q0.read();
}

void guess_babay::thread_tmp_91_fu_516_p1() {
    tmp_91_fu_516_p1 = esl_zext<64,4>(row1_reg_192.read());
}

void guess_babay::thread_tmp_93_fu_407_p2() {
    tmp_93_fu_407_p2 = (tmp_105_fu_401_p2.read() & tmp_106_fu_253_p2.read());
}

void guess_babay::thread_tmp_94_fu_491_p2() {
    tmp_94_fu_491_p2 = (!col2_reg_216.read().is_01() || !row1_reg_192.read().is_01())? sc_lv<1>(): (sc_biguint<4>(col2_reg_216.read()) > sc_biguint<4>(row1_reg_192.read()));
}

void guess_babay::thread_tmp_95_fu_497_p2() {
    tmp_95_fu_497_p2 = (!tmp_82_reg_596.read().is_01() || !col2_cast2_fu_475_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_82_reg_596.read()) + sc_biguint<9>(col2_cast2_fu_475_p1.read()));
}

void guess_babay::thread_tmp_96_cast_fu_502_p1() {
    tmp_96_cast_fu_502_p1 = esl_sext<32,9>(tmp_95_fu_497_p2.read());
}

void guess_babay::thread_tmp_96_fu_506_p1() {
    tmp_96_fu_506_p1 = esl_zext<64,32>(tmp_96_cast_fu_502_p1.read());
}

void guess_babay::thread_tmp_97_fu_511_p1() {
    tmp_97_fu_511_p1 = esl_zext<64,4>(col2_reg_216.read());
}

void guess_babay::thread_tmp_99_fu_363_p4() {
    tmp_99_fu_363_p4 = tmp_83_to_int_fu_359_p1.read().range(30, 23);
}

void guess_babay::thread_tmp_fu_289_p1() {
    tmp_fu_289_p1 = esl_zext<64,4>(row_reg_146.read());
}

void guess_babay::thread_tmp_s_fu_318_p2() {
    tmp_s_fu_318_p2 = (!p_shl_cast_fu_302_p1.read().is_01() || !p_shl6_cast_fu_314_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl_cast_fu_302_p1.read()) - sc_biguint<9>(p_shl6_cast_fu_314_p1.read()));
}

void guess_babay::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_277_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond2_fu_328_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(exitcond1_fu_433_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(exitcond_fu_479_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<29>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

