// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "guess_edu.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic guess_edu::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic guess_edu::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<25> guess_edu::ap_ST_fsm_state1 = "1";
const sc_lv<25> guess_edu::ap_ST_fsm_state2 = "10";
const sc_lv<25> guess_edu::ap_ST_fsm_state3 = "100";
const sc_lv<25> guess_edu::ap_ST_fsm_state4 = "1000";
const sc_lv<25> guess_edu::ap_ST_fsm_state5 = "10000";
const sc_lv<25> guess_edu::ap_ST_fsm_state6 = "100000";
const sc_lv<25> guess_edu::ap_ST_fsm_state7 = "1000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state8 = "10000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state9 = "100000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state10 = "1000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state11 = "10000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state12 = "100000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<25> guess_edu::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<32> guess_edu::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> guess_edu::ap_const_lv32_A = "1010";
const sc_lv<1> guess_edu::ap_const_lv1_0 = "0";
const sc_lv<32> guess_edu::ap_const_lv32_14 = "10100";
const sc_lv<32> guess_edu::ap_const_lv32_1 = "1";
const sc_lv<32> guess_edu::ap_const_lv32_2 = "10";
const sc_lv<32> guess_edu::ap_const_lv32_4 = "100";
const sc_lv<32> guess_edu::ap_const_lv32_6 = "110";
const sc_lv<32> guess_edu::ap_const_lv32_7 = "111";
const sc_lv<1> guess_edu::ap_const_lv1_1 = "1";
const sc_lv<32> guess_edu::ap_const_lv32_8 = "1000";
const sc_lv<32> guess_edu::ap_const_lv32_E = "1110";
const sc_lv<32> guess_edu::ap_const_lv32_F = "1111";
const sc_lv<32> guess_edu::ap_const_lv32_12 = "10010";
const sc_lv<32> guess_edu::ap_const_lv32_18 = "11000";
const sc_lv<4> guess_edu::ap_const_lv4_0 = "0000";
const sc_lv<32> guess_edu::ap_const_lv32_3 = "11";
const sc_lv<4> guess_edu::ap_const_lv4_9 = "1001";
const sc_lv<32> guess_edu::ap_const_lv32_5 = "101";
const sc_lv<32> guess_edu::ap_const_lv32_B = "1011";
const sc_lv<32> guess_edu::ap_const_lv32_15 = "10101";
const sc_lv<32> guess_edu::ap_const_lv32_9 = "1001";
const sc_lv<32> guess_edu::ap_const_lv32_13 = "10011";
const sc_lv<4> guess_edu::ap_const_lv4_1 = "1";
const sc_lv<4> guess_edu::ap_const_lv4_B = "1011";
const sc_lv<4> guess_edu::ap_const_lv4_C = "1100";
const sc_lv<4> guess_edu::ap_const_lv4_3 = "11";
const sc_lv<2> guess_edu::ap_const_lv2_0 = "00";
const sc_lv<2> guess_edu::ap_const_lv2_1 = "1";
const bool guess_edu::ap_const_boolean_1 = true;

guess_edu::guess_edu(sc_module_name name) : sc_module(name), mVcdFile(0) {
    u_educated_U = new guess_edu_u_educaibs("u_educated_U");
    u_educated_U->clk(ap_clk);
    u_educated_U->reset(ap_rst);
    u_educated_U->address0(u_educated_address0);
    u_educated_U->ce0(u_educated_ce0);
    u_educated_U->we0(u_educated_we0);
    u_educated_U->d0(u_educated_d0);
    u_educated_U->q0(u_educated_q0);
    predictive_controbkb_U30 = new predictive_controbkb<1,4,32,32,32>("predictive_controbkb_U30");
    predictive_controbkb_U30->clk(ap_clk);
    predictive_controbkb_U30->reset(ap_rst);
    predictive_controbkb_U30->din0(grp_fu_221_p0);
    predictive_controbkb_U30->din1(grp_fu_221_p1);
    predictive_controbkb_U30->opcode(grp_fu_221_opcode);
    predictive_controbkb_U30->ce(ap_var_for_const0);
    predictive_controbkb_U30->dout(grp_fu_221_p2);
    predictive_controcud_U31 = new predictive_controcud<1,2,32,32,32>("predictive_controcud_U31");
    predictive_controcud_U31->clk(ap_clk);
    predictive_controcud_U31->reset(ap_rst);
    predictive_controcud_U31->din0(grp_fu_229_p0);
    predictive_controcud_U31->din1(grp_fu_229_p1);
    predictive_controcud_U31->ce(ap_var_for_const0);
    predictive_controcud_U31->dout(grp_fu_229_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_U_KK_a_address0);
    sensitive << ( tmp_71_fu_261_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_73_fu_290_p1 );

    SC_METHOD(thread_U_KK_a_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_U_unc_kk_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_76_fu_383_p1 );

    SC_METHOD(thread_U_unc_kk_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_V_Gen_a_cpy_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_79_fu_373_p1 );

    SC_METHOD(thread_V_Gen_a_cpy_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond1_fu_300_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond1_fu_300_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond1_fu_300_p2 );
    sensitive << ( educated_rho_reg_174 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_col_4_fu_352_p2);
    sensitive << ( col_reg_210 );

    SC_METHOD(thread_col_cast2_fu_342_p1);
    sensitive << ( col_reg_210 );

    SC_METHOD(thread_exitcond1_fu_300_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( row_reg_186 );

    SC_METHOD(thread_exitcond2_fu_272_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_162 );

    SC_METHOD(thread_exitcond3_fu_255_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_reg_151 );

    SC_METHOD(thread_exitcond_fu_346_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( col_reg_210 );

    SC_METHOD(thread_grp_fu_221_opcode);
    sensitive << ( tmp_77_reg_455 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_fu_221_p0);
    sensitive << ( U_unc_kk_q0 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( educated_rho_reg_174 );
    sensitive << ( temp_value_reg_198 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_fu_221_p1);
    sensitive << ( reg_233 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( temp_value_reg_198 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_fu_229_p0);
    sensitive << ( V_Gen_a_cpy_load_reg_475 );
    sensitive << ( temp_value_2_reg_495 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_grp_fu_229_p1);
    sensitive << ( u_educated_load_reg_480 );
    sensitive << ( temp_value_2_reg_495 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_i_3_fu_266_p2);
    sensitive << ( i_reg_151 );

    SC_METHOD(thread_i_4_fu_278_p2);
    sensitive << ( i1_reg_162 );

    SC_METHOD(thread_indvarinc_fu_238_p2);
    sensitive << ( invdar_reg_140 );

    SC_METHOD(thread_p_shl5_cast_fu_332_p1);
    sensitive << ( p_shl5_fu_324_p3 );

    SC_METHOD(thread_p_shl5_fu_324_p3);
    sensitive << ( row_reg_186 );

    SC_METHOD(thread_p_shl_cast_fu_320_p1);
    sensitive << ( p_shl_fu_312_p3 );

    SC_METHOD(thread_p_shl_fu_312_p3);
    sensitive << ( row_reg_186 );

    SC_METHOD(thread_row_14_fu_306_p2);
    sensitive << ( row_reg_186 );

    SC_METHOD(thread_temp_value_1_fu_388_p3);
    sensitive << ( tmp_77_reg_455 );
    sensitive << ( grp_fu_221_p2 );
    sensitive << ( temp_value_reg_198 );

    SC_METHOD(thread_tmp_71_fu_261_p1);
    sensitive << ( i_reg_151 );

    SC_METHOD(thread_tmp_72_fu_284_p2);
    sensitive << ( i1_reg_162 );

    SC_METHOD(thread_tmp_73_fu_290_p1);
    sensitive << ( tmp_72_fu_284_p2 );

    SC_METHOD(thread_tmp_74_fu_295_p1);
    sensitive << ( i1_reg_162 );

    SC_METHOD(thread_tmp_75_fu_336_p2);
    sensitive << ( p_shl_cast_fu_320_p1 );
    sensitive << ( p_shl5_cast_fu_332_p1 );

    SC_METHOD(thread_tmp_76_fu_383_p1);
    sensitive << ( row_reg_186 );

    SC_METHOD(thread_tmp_77_fu_358_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_346_p2 );
    sensitive << ( row_reg_186 );
    sensitive << ( col_reg_210 );

    SC_METHOD(thread_tmp_78_cast_fu_369_p1);
    sensitive << ( tmp_78_fu_364_p2 );

    SC_METHOD(thread_tmp_78_fu_364_p2);
    sensitive << ( tmp_75_reg_442 );
    sensitive << ( col_cast2_fu_342_p1 );

    SC_METHOD(thread_tmp_79_fu_373_p1);
    sensitive << ( tmp_78_cast_fu_369_p1 );

    SC_METHOD(thread_tmp_80_fu_378_p1);
    sensitive << ( col_reg_210 );

    SC_METHOD(thread_tmp_fu_244_p1);
    sensitive << ( invdar_reg_140 );

    SC_METHOD(thread_tmp_s_fu_249_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( invdar_reg_140 );

    SC_METHOD(thread_u_educated_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_71_reg_406 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_fu_244_p1 );
    sensitive << ( tmp_74_fu_295_p1 );
    sensitive << ( tmp_80_fu_378_p1 );

    SC_METHOD(thread_u_educated_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_u_educated_d0);
    sensitive << ( U_KK_a_q0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_u_educated_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_255_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_272_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond1_fu_300_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_346_p2 );
    sensitive << ( tmp_s_fu_249_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "guess_edu_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, U_KK_a_address0, "(port)U_KK_a_address0");
    sc_trace(mVcdFile, U_KK_a_ce0, "(port)U_KK_a_ce0");
    sc_trace(mVcdFile, U_KK_a_q0, "(port)U_KK_a_q0");
    sc_trace(mVcdFile, V_Gen_a_cpy_address0, "(port)V_Gen_a_cpy_address0");
    sc_trace(mVcdFile, V_Gen_a_cpy_ce0, "(port)V_Gen_a_cpy_ce0");
    sc_trace(mVcdFile, V_Gen_a_cpy_q0, "(port)V_Gen_a_cpy_q0");
    sc_trace(mVcdFile, U_unc_kk_address0, "(port)U_unc_kk_address0");
    sc_trace(mVcdFile, U_unc_kk_ce0, "(port)U_unc_kk_ce0");
    sc_trace(mVcdFile, U_unc_kk_q0, "(port)U_unc_kk_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_229_p2, "grp_fu_229_p2");
    sc_trace(mVcdFile, reg_233, "reg_233");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_77_reg_455, "tmp_77_reg_455");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, indvarinc_fu_238_p2, "indvarinc_fu_238_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_71_fu_261_p1, "tmp_71_fu_261_p1");
    sc_trace(mVcdFile, tmp_71_reg_406, "tmp_71_reg_406");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond3_fu_255_p2, "exitcond3_fu_255_p2");
    sc_trace(mVcdFile, i_3_fu_266_p2, "i_3_fu_266_p2");
    sc_trace(mVcdFile, i_3_reg_416, "i_3_reg_416");
    sc_trace(mVcdFile, i_4_fu_278_p2, "i_4_fu_278_p2");
    sc_trace(mVcdFile, i_4_reg_424, "i_4_reg_424");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond2_fu_272_p2, "exitcond2_fu_272_p2");
    sc_trace(mVcdFile, row_14_fu_306_p2, "row_14_fu_306_p2");
    sc_trace(mVcdFile, row_14_reg_437, "row_14_reg_437");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_75_fu_336_p2, "tmp_75_fu_336_p2");
    sc_trace(mVcdFile, tmp_75_reg_442, "tmp_75_reg_442");
    sc_trace(mVcdFile, exitcond1_fu_300_p2, "exitcond1_fu_300_p2");
    sc_trace(mVcdFile, col_4_fu_352_p2, "col_4_fu_352_p2");
    sc_trace(mVcdFile, col_4_reg_450, "col_4_reg_450");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_77_fu_358_p2, "tmp_77_fu_358_p2");
    sc_trace(mVcdFile, exitcond_fu_346_p2, "exitcond_fu_346_p2");
    sc_trace(mVcdFile, V_Gen_a_cpy_load_reg_475, "V_Gen_a_cpy_load_reg_475");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, u_educated_q0, "u_educated_q0");
    sc_trace(mVcdFile, u_educated_load_reg_480, "u_educated_load_reg_480");
    sc_trace(mVcdFile, temp_value_1_fu_388_p3, "temp_value_1_fu_388_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, grp_fu_221_p2, "grp_fu_221_p2");
    sc_trace(mVcdFile, temp_value_2_reg_495, "temp_value_2_reg_495");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, u_educated_address0, "u_educated_address0");
    sc_trace(mVcdFile, u_educated_ce0, "u_educated_ce0");
    sc_trace(mVcdFile, u_educated_we0, "u_educated_we0");
    sc_trace(mVcdFile, u_educated_d0, "u_educated_d0");
    sc_trace(mVcdFile, invdar_reg_140, "invdar_reg_140");
    sc_trace(mVcdFile, tmp_s_fu_249_p2, "tmp_s_fu_249_p2");
    sc_trace(mVcdFile, i_reg_151, "i_reg_151");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i1_reg_162, "i1_reg_162");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, educated_rho_reg_174, "educated_rho_reg_174");
    sc_trace(mVcdFile, row_reg_186, "row_reg_186");
    sc_trace(mVcdFile, temp_value_reg_198, "temp_value_reg_198");
    sc_trace(mVcdFile, col_reg_210, "col_reg_210");
    sc_trace(mVcdFile, tmp_fu_244_p1, "tmp_fu_244_p1");
    sc_trace(mVcdFile, tmp_73_fu_290_p1, "tmp_73_fu_290_p1");
    sc_trace(mVcdFile, tmp_74_fu_295_p1, "tmp_74_fu_295_p1");
    sc_trace(mVcdFile, tmp_79_fu_373_p1, "tmp_79_fu_373_p1");
    sc_trace(mVcdFile, tmp_80_fu_378_p1, "tmp_80_fu_378_p1");
    sc_trace(mVcdFile, tmp_76_fu_383_p1, "tmp_76_fu_383_p1");
    sc_trace(mVcdFile, grp_fu_221_p0, "grp_fu_221_p0");
    sc_trace(mVcdFile, grp_fu_221_p1, "grp_fu_221_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, grp_fu_229_p0, "grp_fu_229_p0");
    sc_trace(mVcdFile, grp_fu_229_p1, "grp_fu_229_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, tmp_72_fu_284_p2, "tmp_72_fu_284_p2");
    sc_trace(mVcdFile, p_shl_fu_312_p3, "p_shl_fu_312_p3");
    sc_trace(mVcdFile, p_shl5_fu_324_p3, "p_shl5_fu_324_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_320_p1, "p_shl_cast_fu_320_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_332_p1, "p_shl5_cast_fu_332_p1");
    sc_trace(mVcdFile, col_cast2_fu_342_p1, "col_cast2_fu_342_p1");
    sc_trace(mVcdFile, tmp_78_fu_364_p2, "tmp_78_fu_364_p2");
    sc_trace(mVcdFile, tmp_78_cast_fu_369_p1, "tmp_78_cast_fu_369_p1");
    sc_trace(mVcdFile, grp_fu_221_opcode, "grp_fu_221_opcode");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

guess_edu::~guess_edu() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete u_educated_U;
    delete predictive_controbkb_U30;
    delete predictive_controcud_U31;
}

void guess_edu::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void guess_edu::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
             esl_seteq<1,1,1>(exitcond1_fu_300_p2.read(), ap_const_lv1_1))) {
            ap_return_preg = educated_rho_reg_174.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        col_reg_210 = col_4_reg_450.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_300_p2.read()))) {
        col_reg_210 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_272_p2.read(), ap_const_lv1_1))) {
        educated_rho_reg_174 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        educated_rho_reg_174 = grp_fu_221_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_255_p2.read(), ap_const_lv1_1))) {
        i1_reg_162 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i1_reg_162 = i_4_reg_424.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_249_p2.read()))) {
        i_reg_151 = ap_const_lv4_9;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_151 = i_3_reg_416.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_249_p2.read()))) {
        invdar_reg_140 = indvarinc_fu_238_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        invdar_reg_140 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_272_p2.read(), ap_const_lv1_1))) {
        row_reg_186 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        row_reg_186 = row_14_reg_437.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        temp_value_reg_198 = temp_value_1_fu_388_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_300_p2.read()))) {
        temp_value_reg_198 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        V_Gen_a_cpy_load_reg_475 = V_Gen_a_cpy_q0.read();
        u_educated_load_reg_480 = u_educated_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        col_4_reg_450 = col_4_fu_352_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_255_p2.read()))) {
        i_3_reg_416 = i_3_fu_266_p2.read();
        tmp_71_reg_406 = tmp_71_fu_261_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_4_reg_424 = i_4_fu_278_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
  esl_seteq<1,1,1>(tmp_77_reg_455.read(), ap_const_lv1_0)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        reg_233 = grp_fu_229_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        row_14_reg_437 = row_14_fu_306_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        temp_value_2_reg_495 = grp_fu_221_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_300_p2.read()))) {
        tmp_75_reg_442 = tmp_75_fu_336_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_346_p2.read()))) {
        tmp_77_reg_455 = tmp_77_fu_358_p2.read();
    }
}

void guess_edu::thread_U_KK_a_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        U_KK_a_address0 =  (sc_lv<4>) (tmp_73_fu_290_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        U_KK_a_address0 =  (sc_lv<4>) (tmp_71_fu_261_p1.read());
    } else {
        U_KK_a_address0 = "XXXX";
    }
}

void guess_edu::thread_U_KK_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        U_KK_a_ce0 = ap_const_logic_1;
    } else {
        U_KK_a_ce0 = ap_const_logic_0;
    }
}

void guess_edu::thread_U_unc_kk_address0() {
    U_unc_kk_address0 =  (sc_lv<4>) (tmp_76_fu_383_p1.read());
}

void guess_edu::thread_U_unc_kk_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        U_unc_kk_ce0 = ap_const_logic_1;
    } else {
        U_unc_kk_ce0 = ap_const_logic_0;
    }
}

void guess_edu::thread_V_Gen_a_cpy_address0() {
    V_Gen_a_cpy_address0 =  (sc_lv<8>) (tmp_79_fu_373_p1.read());
}

void guess_edu::thread_V_Gen_a_cpy_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        V_Gen_a_cpy_ce0 = ap_const_logic_1;
    } else {
        V_Gen_a_cpy_ce0 = ap_const_logic_0;
    }
}

void guess_edu::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void guess_edu::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void guess_edu::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void guess_edu::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void guess_edu::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void guess_edu::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void guess_edu::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void guess_edu::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void guess_edu::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void guess_edu::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void guess_edu::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void guess_edu::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void guess_edu::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void guess_edu::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void guess_edu::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void guess_edu::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void guess_edu::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void guess_edu::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void guess_edu::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void guess_edu::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_300_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void guess_edu::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void guess_edu::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_300_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void guess_edu::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_300_p2.read(), ap_const_lv1_1))) {
        ap_return = educated_rho_reg_174.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void guess_edu::thread_col_4_fu_352_p2() {
    col_4_fu_352_p2 = (!col_reg_210.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_reg_210.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_edu::thread_col_cast2_fu_342_p1() {
    col_cast2_fu_342_p1 = esl_zext<9,4>(col_reg_210.read());
}

void guess_edu::thread_exitcond1_fu_300_p2() {
    exitcond1_fu_300_p2 = (!row_reg_186.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_186.read() == ap_const_lv4_C);
}

void guess_edu::thread_exitcond2_fu_272_p2() {
    exitcond2_fu_272_p2 = (!i1_reg_162.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_162.read() == ap_const_lv4_9);
}

void guess_edu::thread_exitcond3_fu_255_p2() {
    exitcond3_fu_255_p2 = (!i_reg_151.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_151.read() == ap_const_lv4_C);
}

void guess_edu::thread_exitcond_fu_346_p2() {
    exitcond_fu_346_p2 = (!col_reg_210.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_210.read() == ap_const_lv4_C);
}

void guess_edu::thread_grp_fu_221_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        grp_fu_221_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
                (esl_seteq<1,1,1>(tmp_77_reg_455.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())))) {
        grp_fu_221_opcode = ap_const_lv2_0;
    } else {
        grp_fu_221_opcode =  (sc_lv<2>) ("XX");
    }
}

void guess_edu::thread_grp_fu_221_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_fu_221_p0 = educated_rho_reg_174.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        grp_fu_221_p0 = U_unc_kk_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_221_p0 = temp_value_reg_198.read();
    } else {
        grp_fu_221_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_edu::thread_grp_fu_221_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        grp_fu_221_p1 = temp_value_reg_198.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        grp_fu_221_p1 = reg_233.read();
    } else {
        grp_fu_221_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_edu::thread_grp_fu_229_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_229_p0 = temp_value_2_reg_495.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_229_p0 = V_Gen_a_cpy_load_reg_475.read();
    } else {
        grp_fu_229_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_edu::thread_grp_fu_229_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_229_p1 = temp_value_2_reg_495.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_229_p1 = u_educated_load_reg_480.read();
    } else {
        grp_fu_229_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_edu::thread_i_3_fu_266_p2() {
    i_3_fu_266_p2 = (!i_reg_151.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_151.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_edu::thread_i_4_fu_278_p2() {
    i_4_fu_278_p2 = (!i1_reg_162.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_reg_162.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_edu::thread_indvarinc_fu_238_p2() {
    indvarinc_fu_238_p2 = (!invdar_reg_140.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(invdar_reg_140.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_edu::thread_p_shl5_cast_fu_332_p1() {
    p_shl5_cast_fu_332_p1 = esl_zext<9,6>(p_shl5_fu_324_p3.read());
}

void guess_edu::thread_p_shl5_fu_324_p3() {
    p_shl5_fu_324_p3 = esl_concat<4,2>(row_reg_186.read(), ap_const_lv2_0);
}

void guess_edu::thread_p_shl_cast_fu_320_p1() {
    p_shl_cast_fu_320_p1 = esl_zext<9,8>(p_shl_fu_312_p3.read());
}

void guess_edu::thread_p_shl_fu_312_p3() {
    p_shl_fu_312_p3 = esl_concat<4,4>(row_reg_186.read(), ap_const_lv4_0);
}

void guess_edu::thread_row_14_fu_306_p2() {
    row_14_fu_306_p2 = (!row_reg_186.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_reg_186.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void guess_edu::thread_temp_value_1_fu_388_p3() {
    temp_value_1_fu_388_p3 = (!tmp_77_reg_455.read()[0].is_01())? sc_lv<32>(): ((tmp_77_reg_455.read()[0].to_bool())? temp_value_reg_198.read(): grp_fu_221_p2.read());
}

void guess_edu::thread_tmp_71_fu_261_p1() {
    tmp_71_fu_261_p1 = esl_zext<64,4>(i_reg_151.read());
}

void guess_edu::thread_tmp_72_fu_284_p2() {
    tmp_72_fu_284_p2 = (!i1_reg_162.read().is_01() || !ap_const_lv4_3.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_reg_162.read()) + sc_biguint<4>(ap_const_lv4_3));
}

void guess_edu::thread_tmp_73_fu_290_p1() {
    tmp_73_fu_290_p1 = esl_zext<64,4>(tmp_72_fu_284_p2.read());
}

void guess_edu::thread_tmp_74_fu_295_p1() {
    tmp_74_fu_295_p1 = esl_zext<64,4>(i1_reg_162.read());
}

void guess_edu::thread_tmp_75_fu_336_p2() {
    tmp_75_fu_336_p2 = (!p_shl_cast_fu_320_p1.read().is_01() || !p_shl5_cast_fu_332_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl_cast_fu_320_p1.read()) - sc_biguint<9>(p_shl5_cast_fu_332_p1.read()));
}

void guess_edu::thread_tmp_76_fu_383_p1() {
    tmp_76_fu_383_p1 = esl_zext<64,4>(row_reg_186.read());
}

void guess_edu::thread_tmp_77_fu_358_p2() {
    tmp_77_fu_358_p2 = (!col_reg_210.read().is_01() || !row_reg_186.read().is_01())? sc_lv<1>(): (sc_biguint<4>(col_reg_210.read()) > sc_biguint<4>(row_reg_186.read()));
}

void guess_edu::thread_tmp_78_cast_fu_369_p1() {
    tmp_78_cast_fu_369_p1 = esl_sext<32,9>(tmp_78_fu_364_p2.read());
}

void guess_edu::thread_tmp_78_fu_364_p2() {
    tmp_78_fu_364_p2 = (!tmp_75_reg_442.read().is_01() || !col_cast2_fu_342_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_75_reg_442.read()) + sc_biguint<9>(col_cast2_fu_342_p1.read()));
}

void guess_edu::thread_tmp_79_fu_373_p1() {
    tmp_79_fu_373_p1 = esl_zext<64,32>(tmp_78_cast_fu_369_p1.read());
}

void guess_edu::thread_tmp_80_fu_378_p1() {
    tmp_80_fu_378_p1 = esl_zext<64,4>(col_reg_210.read());
}

void guess_edu::thread_tmp_fu_244_p1() {
    tmp_fu_244_p1 = esl_zext<64,4>(invdar_reg_140.read());
}

void guess_edu::thread_tmp_s_fu_249_p2() {
    tmp_s_fu_249_p2 = (!invdar_reg_140.read().is_01() || !ap_const_lv4_B.is_01())? sc_lv<1>(): sc_lv<1>(invdar_reg_140.read() == ap_const_lv4_B);
}

void guess_edu::thread_u_educated_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        u_educated_address0 =  (sc_lv<4>) (tmp_80_fu_378_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        u_educated_address0 =  (sc_lv<4>) (tmp_74_fu_295_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        u_educated_address0 =  (sc_lv<4>) (tmp_71_reg_406.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        u_educated_address0 =  (sc_lv<4>) (tmp_fu_244_p1.read());
    } else {
        u_educated_address0 = "XXXX";
    }
}

void guess_edu::thread_u_educated_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        u_educated_ce0 = ap_const_logic_1;
    } else {
        u_educated_ce0 = ap_const_logic_0;
    }
}

void guess_edu::thread_u_educated_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        u_educated_d0 = U_KK_a_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        u_educated_d0 = ap_const_lv32_0;
    } else {
        u_educated_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void guess_edu::thread_u_educated_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        u_educated_we0 = ap_const_logic_1;
    } else {
        u_educated_we0 = ap_const_logic_0;
    }
}

void guess_edu::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_249_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond3_fu_255_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_272_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(exitcond1_fu_300_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(exitcond_fu_346_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<25>) ("XXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

