// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _guess_babay_HH_
#define _guess_babay_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "predictive_controbkb.h"
#include "predictive_controcud.h"
#include "predictive_controjbC.h"
#include "guess_edu_u_educaibs.h"

namespace ap_rtl {

struct guess_babay : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > V_Gen_a_address0;
    sc_out< sc_logic > V_Gen_a_ce0;
    sc_in< sc_lv<32> > V_Gen_a_q0;
    sc_out< sc_lv<8> > H_Hat_Inv_a_address0;
    sc_out< sc_logic > H_Hat_Inv_a_ce0;
    sc_in< sc_lv<32> > H_Hat_Inv_a_q0;
    sc_out< sc_lv<4> > U_unc_kk_address0;
    sc_out< sc_logic > U_unc_kk_ce0;
    sc_in< sc_lv<32> > U_unc_kk_q0;
    sc_out< sc_lv<4> > theta_kk_address0;
    sc_out< sc_logic > theta_kk_ce0;
    sc_in< sc_lv<32> > theta_kk_q0;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<32> > ap_var_for_const4;
    sc_signal< sc_lv<5> > ap_var_for_const2;
    sc_signal< sc_lv<5> > ap_var_for_const3;


    // Module declarations
    guess_babay(sc_module_name name);
    SC_HAS_PROCESS(guess_babay);

    ~guess_babay();

    sc_trace_file* mVcdFile;

    guess_edu_u_educaibs* U_babay_U;
    predictive_controbkb<1,4,32,32,32>* predictive_controbkb_U36;
    predictive_controcud<1,2,32,32,32>* predictive_controcud_U37;
    predictive_controjbC<1,1,32,32,1>* predictive_controjbC_U38;
    predictive_controjbC<1,1,32,32,1>* predictive_controjbC_U39;
    predictive_controjbC<1,1,32,32,1>* predictive_controjbC_U40;
    predictive_controjbC<1,1,32,32,1>* predictive_controjbC_U41;
    sc_signal< sc_lv<29> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_237_p2;
    sc_signal< sc_lv<32> > reg_265;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<1> > tmp_94_reg_609;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > grp_fu_227_p2;
    sc_signal< sc_lv<32> > reg_270;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<4> > row_15_fu_283_p2;
    sc_signal< sc_lv<4> > row_15_reg_531;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<4> > U_babay_addr_reg_536;
    sc_signal< sc_lv<1> > exitcond3_fu_277_p2;
    sc_signal< sc_lv<9> > tmp_s_fu_318_p2;
    sc_signal< sc_lv<9> > tmp_s_reg_541;
    sc_signal< sc_lv<4> > col_5_fu_334_p2;
    sc_signal< sc_lv<4> > col_5_reg_549;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond2_fu_328_p2;
    sc_signal< sc_lv<32> > tmp_88_neg_fu_423_p2;
    sc_signal< sc_lv<32> > tmp_88_neg_reg_573;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > theta_kk_load_reg_578;
    sc_signal< sc_lv<32> > tmp_87_fu_429_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > row_1_fu_439_p2;
    sc_signal< sc_lv<4> > row_1_reg_591;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<9> > tmp_82_fu_469_p2;
    sc_signal< sc_lv<9> > tmp_82_reg_596;
    sc_signal< sc_lv<1> > exitcond1_fu_433_p2;
    sc_signal< sc_lv<4> > col_6_fu_485_p2;
    sc_signal< sc_lv<4> > col_6_reg_604;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > tmp_94_fu_491_p2;
    sc_signal< sc_lv<1> > exitcond_fu_479_p2;
    sc_signal< sc_lv<32> > V_Gen_a_load_reg_629;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<32> > U_babay_q0;
    sc_signal< sc_lv<32> > U_babay_load_reg_634;
    sc_signal< sc_lv<32> > temp_value_1_fu_521_p3;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_logic > ap_CS_fsm_state29;
    sc_signal< sc_lv<4> > U_babay_address0;
    sc_signal< sc_logic > U_babay_ce0;
    sc_signal< sc_logic > U_babay_we0;
    sc_signal< sc_lv<32> > U_babay_d0;
    sc_signal< sc_lv<4> > row_reg_146;
    sc_signal< sc_lv<32> > tmp_83_reg_157;
    sc_signal< sc_lv<4> > col_reg_169;
    sc_signal< sc_lv<32> > babay_rho_reg_180;
    sc_signal< sc_lv<4> > row1_reg_192;
    sc_signal< sc_lv<32> > temp_value_reg_204;
    sc_signal< sc_lv<4> > col2_reg_216;
    sc_signal< sc_lv<64> > tmp_fu_289_p1;
    sc_signal< sc_lv<64> > tmp_86_fu_349_p1;
    sc_signal< sc_lv<64> > tmp_88_fu_354_p1;
    sc_signal< sc_lv<64> > tmp_96_fu_506_p1;
    sc_signal< sc_lv<64> > tmp_97_fu_511_p1;
    sc_signal< sc_lv<64> > tmp_91_fu_516_p1;
    sc_signal< sc_lv<1> > tmp_103_fu_395_p2;
    sc_signal< sc_lv<1> > tmp_93_fu_407_p2;
    sc_signal< sc_lv<1> > tmp_108_fu_413_p2;
    sc_signal< sc_lv<32> > grp_fu_227_p0;
    sc_signal< sc_lv<32> > grp_fu_227_p1;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<32> > grp_fu_237_p0;
    sc_signal< sc_lv<32> > grp_fu_237_p1;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<8> > p_shl_fu_294_p3;
    sc_signal< sc_lv<6> > p_shl6_fu_306_p3;
    sc_signal< sc_lv<9> > p_shl_cast_fu_302_p1;
    sc_signal< sc_lv<9> > p_shl6_cast_fu_314_p1;
    sc_signal< sc_lv<9> > col_cast7_fu_324_p1;
    sc_signal< sc_lv<9> > tmp_85_fu_340_p2;
    sc_signal< sc_lv<32> > tmp_85_cast_fu_345_p1;
    sc_signal< sc_lv<32> > tmp_83_to_int_fu_359_p1;
    sc_signal< sc_lv<8> > tmp_99_fu_363_p4;
    sc_signal< sc_lv<23> > tmp_100_fu_373_p1;
    sc_signal< sc_lv<1> > notrhs_fu_383_p2;
    sc_signal< sc_lv<1> > notlhs_fu_377_p2;
    sc_signal< sc_lv<1> > tmp_101_fu_389_p2;
    sc_signal< sc_lv<1> > tmp_102_fu_241_p2;
    sc_signal< sc_lv<1> > tmp_104_fu_247_p2;
    sc_signal< sc_lv<1> > tmp_105_fu_401_p2;
    sc_signal< sc_lv<1> > tmp_106_fu_253_p2;
    sc_signal< sc_lv<1> > tmp_107_fu_259_p2;
    sc_signal< sc_lv<32> > tmp_88_to_int_fu_419_p1;
    sc_signal< sc_lv<8> > p_shl7_fu_445_p3;
    sc_signal< sc_lv<6> > p_shl8_fu_457_p3;
    sc_signal< sc_lv<9> > p_shl7_cast_fu_453_p1;
    sc_signal< sc_lv<9> > p_shl8_cast_fu_465_p1;
    sc_signal< sc_lv<9> > col2_cast2_fu_475_p1;
    sc_signal< sc_lv<9> > tmp_95_fu_497_p2;
    sc_signal< sc_lv<32> > tmp_96_cast_fu_502_p1;
    sc_signal< sc_lv<2> > grp_fu_227_opcode;
    sc_signal< sc_lv<32> > ap_return_preg;
    sc_signal< sc_lv<29> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<29> ap_ST_fsm_state1;
    static const sc_lv<29> ap_ST_fsm_state2;
    static const sc_lv<29> ap_ST_fsm_state3;
    static const sc_lv<29> ap_ST_fsm_state4;
    static const sc_lv<29> ap_ST_fsm_state5;
    static const sc_lv<29> ap_ST_fsm_state6;
    static const sc_lv<29> ap_ST_fsm_state7;
    static const sc_lv<29> ap_ST_fsm_state8;
    static const sc_lv<29> ap_ST_fsm_state9;
    static const sc_lv<29> ap_ST_fsm_state10;
    static const sc_lv<29> ap_ST_fsm_state11;
    static const sc_lv<29> ap_ST_fsm_state12;
    static const sc_lv<29> ap_ST_fsm_state13;
    static const sc_lv<29> ap_ST_fsm_state14;
    static const sc_lv<29> ap_ST_fsm_state15;
    static const sc_lv<29> ap_ST_fsm_state16;
    static const sc_lv<29> ap_ST_fsm_state17;
    static const sc_lv<29> ap_ST_fsm_state18;
    static const sc_lv<29> ap_ST_fsm_state19;
    static const sc_lv<29> ap_ST_fsm_state20;
    static const sc_lv<29> ap_ST_fsm_state21;
    static const sc_lv<29> ap_ST_fsm_state22;
    static const sc_lv<29> ap_ST_fsm_state23;
    static const sc_lv<29> ap_ST_fsm_state24;
    static const sc_lv<29> ap_ST_fsm_state25;
    static const sc_lv<29> ap_ST_fsm_state26;
    static const sc_lv<29> ap_ST_fsm_state27;
    static const sc_lv<29> ap_ST_fsm_state28;
    static const sc_lv<29> ap_ST_fsm_state29;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_BF800000;
    static const sc_lv<32> ap_const_lv32_3F800000;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_3F000000;
    static const sc_lv<32> ap_const_lv32_BF000000;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_80000000;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_3;
    static const sc_lv<5> ap_const_lv5_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_clk_no_reset_();
    void thread_H_Hat_Inv_a_address0();
    void thread_H_Hat_Inv_a_ce0();
    void thread_U_babay_address0();
    void thread_U_babay_ce0();
    void thread_U_babay_d0();
    void thread_U_babay_we0();
    void thread_U_unc_kk_address0();
    void thread_U_unc_kk_ce0();
    void thread_V_Gen_a_address0();
    void thread_V_Gen_a_ce0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_col2_cast2_fu_475_p1();
    void thread_col_5_fu_334_p2();
    void thread_col_6_fu_485_p2();
    void thread_col_cast7_fu_324_p1();
    void thread_exitcond1_fu_433_p2();
    void thread_exitcond2_fu_328_p2();
    void thread_exitcond3_fu_277_p2();
    void thread_exitcond_fu_479_p2();
    void thread_grp_fu_227_opcode();
    void thread_grp_fu_227_p0();
    void thread_grp_fu_227_p1();
    void thread_grp_fu_237_p0();
    void thread_grp_fu_237_p1();
    void thread_notlhs_fu_377_p2();
    void thread_notrhs_fu_383_p2();
    void thread_p_shl6_cast_fu_314_p1();
    void thread_p_shl6_fu_306_p3();
    void thread_p_shl7_cast_fu_453_p1();
    void thread_p_shl7_fu_445_p3();
    void thread_p_shl8_cast_fu_465_p1();
    void thread_p_shl8_fu_457_p3();
    void thread_p_shl_cast_fu_302_p1();
    void thread_p_shl_fu_294_p3();
    void thread_row_15_fu_283_p2();
    void thread_row_1_fu_439_p2();
    void thread_temp_value_1_fu_521_p3();
    void thread_theta_kk_address0();
    void thread_theta_kk_ce0();
    void thread_tmp_100_fu_373_p1();
    void thread_tmp_101_fu_389_p2();
    void thread_tmp_103_fu_395_p2();
    void thread_tmp_105_fu_401_p2();
    void thread_tmp_108_fu_413_p2();
    void thread_tmp_82_fu_469_p2();
    void thread_tmp_83_to_int_fu_359_p1();
    void thread_tmp_85_cast_fu_345_p1();
    void thread_tmp_85_fu_340_p2();
    void thread_tmp_86_fu_349_p1();
    void thread_tmp_87_fu_429_p1();
    void thread_tmp_88_fu_354_p1();
    void thread_tmp_88_neg_fu_423_p2();
    void thread_tmp_88_to_int_fu_419_p1();
    void thread_tmp_91_fu_516_p1();
    void thread_tmp_93_fu_407_p2();
    void thread_tmp_94_fu_491_p2();
    void thread_tmp_95_fu_497_p2();
    void thread_tmp_96_cast_fu_502_p1();
    void thread_tmp_96_fu_506_p1();
    void thread_tmp_97_fu_511_p1();
    void thread_tmp_99_fu_363_p4();
    void thread_tmp_fu_289_p1();
    void thread_tmp_s_fu_318_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
