// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sph_dec.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sph_dec::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sph_dec::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<29> sph_dec::ap_ST_fsm_state1 = "1";
const sc_lv<29> sph_dec::ap_ST_fsm_state2 = "10";
const sc_lv<29> sph_dec::ap_ST_fsm_state3 = "100";
const sc_lv<29> sph_dec::ap_ST_fsm_state4 = "1000";
const sc_lv<29> sph_dec::ap_ST_fsm_state5 = "10000";
const sc_lv<29> sph_dec::ap_ST_fsm_state6 = "100000";
const sc_lv<29> sph_dec::ap_ST_fsm_state7 = "1000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state8 = "10000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state9 = "100000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state10 = "1000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state11 = "10000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state12 = "100000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<29> sph_dec::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<32> sph_dec::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sph_dec::ap_const_lv32_D = "1101";
const sc_lv<32> sph_dec::ap_const_lv32_13 = "10011";
const sc_lv<32> sph_dec::ap_const_lv32_1 = "1";
const sc_lv<32> sph_dec::ap_const_lv32_2 = "10";
const sc_lv<1> sph_dec::ap_const_lv1_1 = "1";
const sc_lv<32> sph_dec::ap_const_lv32_3 = "11";
const sc_lv<1> sph_dec::ap_const_lv1_0 = "0";
const sc_lv<32> sph_dec::ap_const_lv32_4 = "100";
const sc_lv<32> sph_dec::ap_const_lv32_5 = "101";
const sc_lv<32> sph_dec::ap_const_lv32_6 = "110";
const sc_lv<32> sph_dec::ap_const_lv32_9 = "1001";
const sc_lv<32> sph_dec::ap_const_lv32_A = "1010";
const sc_lv<32> sph_dec::ap_const_lv32_F = "1111";
const sc_lv<32> sph_dec::ap_const_lv32_14 = "10100";
const sc_lv<32> sph_dec::ap_const_lv32_15 = "10101";
const sc_lv<32> sph_dec::ap_const_lv32_16 = "10110";
const sc_lv<32> sph_dec::ap_const_lv32_1A = "11010";
const sc_lv<32> sph_dec::ap_const_lv32_1B = "11011";
const sc_lv<32> sph_dec::ap_const_lv32_1C = "11100";
const sc_lv<4> sph_dec::ap_const_lv4_0 = "0000";
const sc_lv<6> sph_dec::ap_const_lv6_0 = "000000";
const sc_lv<32> sph_dec::ap_const_lv32_18 = "11000";
const sc_lv<32> sph_dec::ap_const_lv32_B = "1011";
const sc_lv<32> sph_dec::ap_const_lv32_19 = "11001";
const sc_lv<4> sph_dec::ap_const_lv4_B = "1011";
const sc_lv<64> sph_dec::ap_const_lv64_B = "1011";
const sc_lv<32> sph_dec::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> sph_dec::ap_const_lv32_10 = "10000";
const sc_lv<32> sph_dec::ap_const_lv32_E = "1110";
const sc_lv<64> sph_dec::ap_const_lv64_3EB0C6F7A0B5ED8D = "11111010110000110001101111011110100000101101011110110110001101";
const sc_lv<4> sph_dec::ap_const_lv4_F = "1111";
const sc_lv<4> sph_dec::ap_const_lv4_1 = "1";
const sc_lv<4> sph_dec::ap_const_lv4_C = "1100";
const sc_lv<6> sph_dec::ap_const_lv6_23 = "100011";
const sc_lv<6> sph_dec::ap_const_lv6_1 = "1";
const sc_lv<32> sph_dec::ap_const_lv32_34 = "110100";
const sc_lv<32> sph_dec::ap_const_lv32_3E = "111110";
const sc_lv<11> sph_dec::ap_const_lv11_7FF = "11111111111";
const sc_lv<52> sph_dec::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<32> sph_dec::ap_const_lv32_1F = "11111";
const sc_lv<31> sph_dec::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<2> sph_dec::ap_const_lv2_0 = "00";
const sc_lv<2> sph_dec::ap_const_lv2_1 = "1";
const sc_lv<5> sph_dec::ap_const_lv5_5 = "101";
const bool sph_dec::ap_const_boolean_1 = true;

sph_dec::sph_dec(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dist_array_U = new guess_edu_u_educaibs("dist_array_U");
    dist_array_U->clk(ap_clk);
    dist_array_U->reset(ap_rst);
    dist_array_U->address0(dist_array_address0);
    dist_array_U->ce0(dist_array_ce0);
    dist_array_U->we0(dist_array_we0);
    dist_array_U->d0(dist_array_d0);
    dist_array_U->q0(dist_array_q0);
    switch_point_U = new sph_dec_switch_pokbM("switch_point_U");
    switch_point_U->clk(ap_clk);
    switch_point_U->reset(ap_rst);
    switch_point_U->address0(switch_point_address0);
    switch_point_U->ce0(switch_point_ce0);
    switch_point_U->we0(switch_point_we0);
    switch_point_U->d0(switch_point_d0);
    switch_point_U->q0(switch_point_q0);
    switch_point_U->address1(switch_point_address1);
    switch_point_U->ce1(switch_point_ce1);
    switch_point_U->we1(switch_point_we1);
    switch_point_U->d1(switch_point_d1);
    switch_point_U->q1(switch_point_q1);
    U_U = new guess_edu_u_educaibs("U_U");
    U_U->clk(ap_clk);
    U_U->reset(ap_rst);
    U_U->address0(U_address0);
    U_U->ce0(U_ce0);
    U_U->we0(U_we0);
    U_U->d0(switch_point_q0);
    U_U->q0(U_q0);
    predictive_controbkb_U47 = new predictive_controbkb<1,4,32,32,32>("predictive_controbkb_U47");
    predictive_controbkb_U47->clk(ap_clk);
    predictive_controbkb_U47->reset(ap_rst);
    predictive_controbkb_U47->din0(grp_fu_379_p0);
    predictive_controbkb_U47->din1(grp_fu_379_p1);
    predictive_controbkb_U47->opcode(grp_fu_379_opcode);
    predictive_controbkb_U47->ce(ap_var_for_const0);
    predictive_controbkb_U47->dout(grp_fu_379_p2);
    predictive_controlbW_U48 = new predictive_controlbW<1,4,32,32,32>("predictive_controlbW_U48");
    predictive_controlbW_U48->clk(ap_clk);
    predictive_controlbW_U48->reset(ap_rst);
    predictive_controlbW_U48->din0(dist_matmul_reg_306);
    predictive_controlbW_U48->din1(V_Gen_a_q0);
    predictive_controlbW_U48->ce(ap_var_for_const0);
    predictive_controlbW_U48->dout(grp_fu_385_p2);
    predictive_controcud_U49 = new predictive_controcud<1,2,32,32,32>("predictive_controcud_U49");
    predictive_controcud_U49->clk(ap_clk);
    predictive_controcud_U49->reset(ap_rst);
    predictive_controcud_U49->din0(reg_422);
    predictive_controcud_U49->din1(reg_422);
    predictive_controcud_U49->ce(ap_var_for_const0);
    predictive_controcud_U49->dout(grp_fu_393_p2);
    predictive_contromb6_U50 = new predictive_contromb6<1,3,32,32>("predictive_contromb6_U50");
    predictive_contromb6_U50->clk(ap_clk);
    predictive_contromb6_U50->reset(ap_rst);
    predictive_contromb6_U50->din0(U_q0);
    predictive_contromb6_U50->ce(ap_var_for_const0);
    predictive_contromb6_U50->dout(grp_fu_397_p1);
    predictive_controeOg_U51 = new predictive_controeOg<1,1,32,64>("predictive_controeOg_U51");
    predictive_controeOg_U51->din0(grp_fu_402_p0);
    predictive_controeOg_U51->dout(grp_fu_402_p1);
    predictive_controncg_U52 = new predictive_controncg<1,5,64,64,64>("predictive_controncg_U52");
    predictive_controncg_U52->clk(ap_clk);
    predictive_controncg_U52->reset(ap_rst);
    predictive_controncg_U52->din0(grp_fu_402_p1);
    predictive_controncg_U52->din1(ap_var_for_const1);
    predictive_controncg_U52->ce(ap_var_for_const0);
    predictive_controncg_U52->dout(grp_fu_405_p2);
    predictive_controocq_U53 = new predictive_controocq<1,1,64,64,1>("predictive_controocq_U53");
    predictive_controocq_U53->din0(grp_fu_402_p1);
    predictive_controocq_U53->din1(tmp_41_reg_922);
    predictive_controocq_U53->opcode(ap_var_for_const2);
    predictive_controocq_U53->dout(tmp_66_fu_411_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_U_address0);
    sensitive << ( tmp_36_reg_823 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( tmp_55_fu_722_p1 );
    sensitive << ( tmp_46_fu_525_p1 );

    SC_METHOD(thread_U_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_U_opt_address0);
    sensitive << ( tmp_55_reg_949 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_U_opt_ce0);
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_U_opt_d0);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( grp_fu_397_p1 );

    SC_METHOD(thread_U_opt_we0);
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_U_unc_address0);
    sensitive << ( tmp_36_reg_823 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_U_unc_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_U_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_V_Gen_a_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_50_fu_535_p1 );

    SC_METHOD(thread_V_Gen_a_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_468_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_level_3_ph_phi_fu_332_p6);
    sensitive << ( tmp_67_reg_928 );
    sensitive << ( tmp_45_reg_932 );
    sensitive << ( level_3_ph_reg_329 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_ap_phi_mux_level_4_phi_fu_371_p4);
    sensitive << ( icmp_reg_972 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( level_5_cast_fu_771_p1 );
    sensitive << ( level_4_reg_367 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_468_p2 );

    SC_METHOD(thread_dist_array_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_36_reg_823 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_fu_436_p1 );
    sensitive << ( tmp_48_fu_705_p1 );

    SC_METHOD(thread_dist_array_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_dist_array_d0);
    sensitive << ( reg_422 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_dist_array_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_67_fu_681_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_45_fu_693_p2 );

    SC_METHOD(thread_dist_matmul_3_fu_593_p3);
    sensitive << ( tmp_43_reg_853 );
    sensitive << ( dist_matmul_reg_306 );
    sensitive << ( dist_matmul_5_fu_585_p3 );

    SC_METHOD(thread_dist_matmul_4_fu_562_p3);
    sensitive << ( grp_fu_379_p2 );
    sensitive << ( dist_matmul_reg_306 );
    sensitive << ( sel_tmp1_fu_557_p2 );

    SC_METHOD(thread_dist_matmul_5_fu_585_p3);
    sensitive << ( sel_tmp6_fu_580_p2 );
    sensitive << ( grp_fu_385_p2 );
    sensitive << ( dist_matmul_4_fu_562_p3 );

    SC_METHOD(thread_exitcond1_fu_507_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ii_reg_295 );

    SC_METHOD(thread_exitcond2_fu_468_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i1_reg_284 );

    SC_METHOD(thread_exitcond3_fu_447_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ll_reg_261 );

    SC_METHOD(thread_exitcond_fu_710_p2);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( jj_reg_318 );

    SC_METHOD(thread_grp_fu_379_opcode);
    sensitive << ( tmp_43_reg_853 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_379_p0);
    sensitive << ( U_unc_q0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_38_reg_912 );
    sensitive << ( dist_matmul_reg_306 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_379_p1);
    sensitive << ( V_Gen_a_q0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( dist_array_load_reg_907 );
    sensitive << ( dist_matmul_reg_306 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_402_p0);
    sensitive << ( reg_422 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( p_0_fu_102 );

    SC_METHOD(thread_grp_fu_416_p2);
    sensitive << ( kk_reg_355 );

    SC_METHOD(thread_i_fu_474_p2);
    sensitive << ( i1_reg_284 );

    SC_METHOD(thread_icmp_fu_760_p2);
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( tmp_69_fu_750_p4 );

    SC_METHOD(thread_ii_1_fu_513_p2);
    sensitive << ( ii_reg_295 );

    SC_METHOD(thread_ii_cast_fu_503_p1);
    sensitive << ( ii_reg_295 );

    SC_METHOD(thread_indvarinc_fu_430_p2);
    sensitive << ( invdar_reg_250 );

    SC_METHOD(thread_jj_1_fu_716_p2);
    sensitive << ( jj_reg_318 );

    SC_METHOD(thread_level_1_fu_699_p2);
    sensitive << ( level_reg_272 );

    SC_METHOD(thread_level_5_cast_fu_771_p1);
    sensitive << ( level_2_reg_976 );

    SC_METHOD(thread_ll_1_fu_453_p2);
    sensitive << ( ll_reg_261 );

    SC_METHOD(thread_notlhs1_fu_657_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_54_fu_625_p4 );

    SC_METHOD(thread_notlhs_fu_639_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_42_fu_608_p4 );

    SC_METHOD(thread_notrhs1_fu_663_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_68_fu_635_p1 );

    SC_METHOD(thread_notrhs_fu_645_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_62_fu_618_p1 );

    SC_METHOD(thread_sel_tmp1_fu_557_p2);
    sensitive << ( tmp_47_reg_880 );
    sensitive << ( sel_tmp_fu_552_p2 );

    SC_METHOD(thread_sel_tmp5_demorgan_fu_570_p2);
    sensitive << ( tmp_43_reg_853 );
    sensitive << ( tmp_47_reg_880 );

    SC_METHOD(thread_sel_tmp5_fu_574_p2);
    sensitive << ( sel_tmp5_demorgan_fu_570_p2 );

    SC_METHOD(thread_sel_tmp6_fu_580_p2);
    sensitive << ( tmp_51_reg_892 );
    sensitive << ( sel_tmp5_fu_574_p2 );

    SC_METHOD(thread_sel_tmp_fu_552_p2);
    sensitive << ( tmp_43_reg_853 );

    SC_METHOD(thread_switch_point_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_36_fu_480_p1 );
    sensitive << ( switch_point_addr_2_reg_830 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( switch_point_addr_3_reg_967 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_34_fu_459_p1 );
    sensitive << ( tmp_58_fu_745_p1 );

    SC_METHOD(thread_switch_point_address1);
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( switch_point_addr_4_reg_981 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( tmp_60_fu_766_p1 );

    SC_METHOD(thread_switch_point_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_switch_point_ce1);
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_switch_point_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( tmp_44_fu_687_p2 );
    sensitive << ( tmp_52_fu_732_p2 );

    SC_METHOD(thread_switch_point_d1);
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( switch_point_q1 );

    SC_METHOD(thread_switch_point_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_447_p2 );
    sensitive << ( tmp_67_fu_681_p2 );
    sensitive << ( tmp_67_reg_928 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_45_reg_932 );
    sensitive << ( icmp_fu_760_p2 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_switch_point_we1);
    sensitive << ( icmp_reg_972 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_tmp_34_fu_459_p1);
    sensitive << ( ll_reg_261 );

    SC_METHOD(thread_tmp_36_fu_480_p1);
    sensitive << ( level_reg_272 );

    SC_METHOD(thread_tmp_37_fu_497_p2);
    sensitive << ( tmp_53_fu_485_p2 );
    sensitive << ( tmp_59_fu_491_p2 );

    SC_METHOD(thread_tmp_39_to_int_fu_604_p1);
    sensitive << ( grp_fu_402_p1 );

    SC_METHOD(thread_tmp_41_to_int_fu_622_p1);
    sensitive << ( tmp_41_reg_922 );

    SC_METHOD(thread_tmp_42_fu_608_p4);
    sensitive << ( tmp_39_to_int_fu_604_p1 );

    SC_METHOD(thread_tmp_43_fu_519_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond1_fu_507_p2 );
    sensitive << ( level_reg_272 );
    sensitive << ( ii_cast_fu_503_p1 );

    SC_METHOD(thread_tmp_44_fu_687_p2);
    sensitive << ( switch_point_load_reg_835 );

    SC_METHOD(thread_tmp_45_fu_693_p2);
    sensitive << ( tmp_67_fu_681_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( level_reg_272 );

    SC_METHOD(thread_tmp_46_fu_525_p1);
    sensitive << ( ii_reg_295 );

    SC_METHOD(thread_tmp_47_fu_540_p2);
    sensitive << ( tmp_43_reg_853 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( U_q0 );

    SC_METHOD(thread_tmp_48_fu_705_p1);
    sensitive << ( level_1_fu_699_p2 );

    SC_METHOD(thread_tmp_49_fu_530_p2);
    sensitive << ( tmp_37_reg_840 );
    sensitive << ( ii_cast_fu_503_p1 );

    SC_METHOD(thread_tmp_50_fu_535_p1);
    sensitive << ( tmp_49_fu_530_p2 );

    SC_METHOD(thread_tmp_51_fu_546_p2);
    sensitive << ( tmp_43_reg_853 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( U_q0 );

    SC_METHOD(thread_tmp_52_fu_732_p2);
    sensitive << ( switch_point_q0 );

    SC_METHOD(thread_tmp_53_fu_485_p2);
    sensitive << ( level_reg_272 );

    SC_METHOD(thread_tmp_54_fu_625_p4);
    sensitive << ( tmp_41_to_int_fu_622_p1 );

    SC_METHOD(thread_tmp_55_fu_722_p1);
    sensitive << ( jj_reg_318 );

    SC_METHOD(thread_tmp_57_fu_739_p2);
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( kk_reg_355 );

    SC_METHOD(thread_tmp_58_fu_745_p1);
    sensitive << ( kk_reg_355 );

    SC_METHOD(thread_tmp_59_fu_491_p2);
    sensitive << ( level_reg_272 );

    SC_METHOD(thread_tmp_60_fu_766_p1);
    sensitive << ( grp_fu_416_p2 );

    SC_METHOD(thread_tmp_62_fu_618_p1);
    sensitive << ( tmp_39_to_int_fu_604_p1 );

    SC_METHOD(thread_tmp_63_fu_651_p2);
    sensitive << ( notrhs_fu_645_p2 );
    sensitive << ( notlhs_fu_639_p2 );

    SC_METHOD(thread_tmp_64_fu_669_p2);
    sensitive << ( notrhs1_fu_663_p2 );
    sensitive << ( notlhs1_fu_657_p2 );

    SC_METHOD(thread_tmp_65_fu_675_p2);
    sensitive << ( tmp_63_fu_651_p2 );
    sensitive << ( tmp_64_fu_669_p2 );

    SC_METHOD(thread_tmp_67_fu_681_p2);
    sensitive << ( tmp_65_fu_675_p2 );
    sensitive << ( tmp_66_fu_411_p2 );

    SC_METHOD(thread_tmp_68_fu_635_p1);
    sensitive << ( tmp_41_to_int_fu_622_p1 );

    SC_METHOD(thread_tmp_69_fu_750_p4);
    sensitive << ( switch_point_q0 );

    SC_METHOD(thread_tmp_fu_436_p1);
    sensitive << ( invdar_reg_250 );

    SC_METHOD(thread_tmp_s_fu_441_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( invdar_reg_250 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_447_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_468_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond1_fu_507_p2 );
    sensitive << ( tmp_67_fu_681_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_45_fu_693_p2 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( exitcond_fu_710_p2 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( tmp_57_fu_739_p2 );
    sensitive << ( tmp_s_fu_441_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "00000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sph_dec_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, V_Gen_a_address0, "(port)V_Gen_a_address0");
    sc_trace(mVcdFile, V_Gen_a_ce0, "(port)V_Gen_a_ce0");
    sc_trace(mVcdFile, V_Gen_a_q0, "(port)V_Gen_a_q0");
    sc_trace(mVcdFile, roh, "(port)roh");
    sc_trace(mVcdFile, U_unc_address0, "(port)U_unc_address0");
    sc_trace(mVcdFile, U_unc_ce0, "(port)U_unc_ce0");
    sc_trace(mVcdFile, U_unc_q0, "(port)U_unc_q0");
    sc_trace(mVcdFile, U_opt_address0, "(port)U_opt_address0");
    sc_trace(mVcdFile, U_opt_ce0, "(port)U_opt_ce0");
    sc_trace(mVcdFile, U_opt_we0, "(port)U_opt_we0");
    sc_trace(mVcdFile, U_opt_d0, "(port)U_opt_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_379_p2, "grp_fu_379_p2");
    sc_trace(mVcdFile, reg_422, "reg_422");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, indvarinc_fu_430_p2, "indvarinc_fu_430_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ll_1_fu_453_p2, "ll_1_fu_453_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond3_fu_447_p2, "exitcond3_fu_447_p2");
    sc_trace(mVcdFile, i_fu_474_p2, "i_fu_474_p2");
    sc_trace(mVcdFile, i_reg_818, "i_reg_818");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_36_fu_480_p1, "tmp_36_fu_480_p1");
    sc_trace(mVcdFile, tmp_36_reg_823, "tmp_36_reg_823");
    sc_trace(mVcdFile, exitcond2_fu_468_p2, "exitcond2_fu_468_p2");
    sc_trace(mVcdFile, switch_point_addr_2_reg_830, "switch_point_addr_2_reg_830");
    sc_trace(mVcdFile, switch_point_q0, "switch_point_q0");
    sc_trace(mVcdFile, switch_point_load_reg_835, "switch_point_load_reg_835");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_37_fu_497_p2, "tmp_37_fu_497_p2");
    sc_trace(mVcdFile, tmp_37_reg_840, "tmp_37_reg_840");
    sc_trace(mVcdFile, ii_1_fu_513_p2, "ii_1_fu_513_p2");
    sc_trace(mVcdFile, ii_1_reg_848, "ii_1_reg_848");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_43_fu_519_p2, "tmp_43_fu_519_p2");
    sc_trace(mVcdFile, tmp_43_reg_853, "tmp_43_reg_853");
    sc_trace(mVcdFile, exitcond1_fu_507_p2, "exitcond1_fu_507_p2");
    sc_trace(mVcdFile, tmp_47_fu_540_p2, "tmp_47_fu_540_p2");
    sc_trace(mVcdFile, tmp_47_reg_880, "tmp_47_reg_880");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_51_fu_546_p2, "tmp_51_fu_546_p2");
    sc_trace(mVcdFile, tmp_51_reg_892, "tmp_51_reg_892");
    sc_trace(mVcdFile, dist_matmul_3_fu_593_p3, "dist_matmul_3_fu_593_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, dist_array_q0, "dist_array_q0");
    sc_trace(mVcdFile, dist_array_load_reg_907, "dist_array_load_reg_907");
    sc_trace(mVcdFile, grp_fu_393_p2, "grp_fu_393_p2");
    sc_trace(mVcdFile, tmp_38_reg_912, "tmp_38_reg_912");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, grp_fu_402_p1, "grp_fu_402_p1");
    sc_trace(mVcdFile, grp_fu_405_p2, "grp_fu_405_p2");
    sc_trace(mVcdFile, tmp_41_reg_922, "tmp_41_reg_922");
    sc_trace(mVcdFile, tmp_67_fu_681_p2, "tmp_67_fu_681_p2");
    sc_trace(mVcdFile, tmp_67_reg_928, "tmp_67_reg_928");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_45_fu_693_p2, "tmp_45_fu_693_p2");
    sc_trace(mVcdFile, tmp_45_reg_932, "tmp_45_reg_932");
    sc_trace(mVcdFile, level_1_fu_699_p2, "level_1_fu_699_p2");
    sc_trace(mVcdFile, jj_1_fu_716_p2, "jj_1_fu_716_p2");
    sc_trace(mVcdFile, jj_1_reg_944, "jj_1_reg_944");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, tmp_55_fu_722_p1, "tmp_55_fu_722_p1");
    sc_trace(mVcdFile, tmp_55_reg_949, "tmp_55_reg_949");
    sc_trace(mVcdFile, exitcond_fu_710_p2, "exitcond_fu_710_p2");
    sc_trace(mVcdFile, U_q0, "U_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, switch_point_addr_3_reg_967, "switch_point_addr_3_reg_967");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, tmp_57_fu_739_p2, "tmp_57_fu_739_p2");
    sc_trace(mVcdFile, icmp_fu_760_p2, "icmp_fu_760_p2");
    sc_trace(mVcdFile, icmp_reg_972, "icmp_reg_972");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, grp_fu_416_p2, "grp_fu_416_p2");
    sc_trace(mVcdFile, level_2_reg_976, "level_2_reg_976");
    sc_trace(mVcdFile, switch_point_addr_4_reg_981, "switch_point_addr_4_reg_981");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, dist_array_address0, "dist_array_address0");
    sc_trace(mVcdFile, dist_array_ce0, "dist_array_ce0");
    sc_trace(mVcdFile, dist_array_we0, "dist_array_we0");
    sc_trace(mVcdFile, dist_array_d0, "dist_array_d0");
    sc_trace(mVcdFile, switch_point_address0, "switch_point_address0");
    sc_trace(mVcdFile, switch_point_ce0, "switch_point_ce0");
    sc_trace(mVcdFile, switch_point_we0, "switch_point_we0");
    sc_trace(mVcdFile, switch_point_d0, "switch_point_d0");
    sc_trace(mVcdFile, switch_point_address1, "switch_point_address1");
    sc_trace(mVcdFile, switch_point_ce1, "switch_point_ce1");
    sc_trace(mVcdFile, switch_point_we1, "switch_point_we1");
    sc_trace(mVcdFile, switch_point_d1, "switch_point_d1");
    sc_trace(mVcdFile, switch_point_q1, "switch_point_q1");
    sc_trace(mVcdFile, U_address0, "U_address0");
    sc_trace(mVcdFile, U_ce0, "U_ce0");
    sc_trace(mVcdFile, U_we0, "U_we0");
    sc_trace(mVcdFile, invdar_reg_250, "invdar_reg_250");
    sc_trace(mVcdFile, tmp_s_fu_441_p2, "tmp_s_fu_441_p2");
    sc_trace(mVcdFile, ll_reg_261, "ll_reg_261");
    sc_trace(mVcdFile, level_reg_272, "level_reg_272");
    sc_trace(mVcdFile, i1_reg_284, "i1_reg_284");
    sc_trace(mVcdFile, ii_reg_295, "ii_reg_295");
    sc_trace(mVcdFile, dist_matmul_reg_306, "dist_matmul_reg_306");
    sc_trace(mVcdFile, jj_reg_318, "jj_reg_318");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, ap_phi_mux_level_3_ph_phi_fu_332_p6, "ap_phi_mux_level_3_ph_phi_fu_332_p6");
    sc_trace(mVcdFile, level_3_ph_reg_329, "level_3_ph_reg_329");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, ap_phi_mux_level_4_phi_fu_371_p4, "ap_phi_mux_level_4_phi_fu_371_p4");
    sc_trace(mVcdFile, level_3_reg_343, "level_3_reg_343");
    sc_trace(mVcdFile, kk_reg_355, "kk_reg_355");
    sc_trace(mVcdFile, level_5_cast_fu_771_p1, "level_5_cast_fu_771_p1");
    sc_trace(mVcdFile, level_4_reg_367, "level_4_reg_367");
    sc_trace(mVcdFile, tmp_fu_436_p1, "tmp_fu_436_p1");
    sc_trace(mVcdFile, tmp_34_fu_459_p1, "tmp_34_fu_459_p1");
    sc_trace(mVcdFile, tmp_46_fu_525_p1, "tmp_46_fu_525_p1");
    sc_trace(mVcdFile, tmp_50_fu_535_p1, "tmp_50_fu_535_p1");
    sc_trace(mVcdFile, tmp_48_fu_705_p1, "tmp_48_fu_705_p1");
    sc_trace(mVcdFile, tmp_58_fu_745_p1, "tmp_58_fu_745_p1");
    sc_trace(mVcdFile, tmp_60_fu_766_p1, "tmp_60_fu_766_p1");
    sc_trace(mVcdFile, p_0_fu_102, "p_0_fu_102");
    sc_trace(mVcdFile, tmp_44_fu_687_p2, "tmp_44_fu_687_p2");
    sc_trace(mVcdFile, tmp_52_fu_732_p2, "tmp_52_fu_732_p2");
    sc_trace(mVcdFile, grp_fu_397_p1, "grp_fu_397_p1");
    sc_trace(mVcdFile, grp_fu_379_p0, "grp_fu_379_p0");
    sc_trace(mVcdFile, grp_fu_379_p1, "grp_fu_379_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, grp_fu_402_p0, "grp_fu_402_p0");
    sc_trace(mVcdFile, tmp_53_fu_485_p2, "tmp_53_fu_485_p2");
    sc_trace(mVcdFile, tmp_59_fu_491_p2, "tmp_59_fu_491_p2");
    sc_trace(mVcdFile, ii_cast_fu_503_p1, "ii_cast_fu_503_p1");
    sc_trace(mVcdFile, tmp_49_fu_530_p2, "tmp_49_fu_530_p2");
    sc_trace(mVcdFile, sel_tmp_fu_552_p2, "sel_tmp_fu_552_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_557_p2, "sel_tmp1_fu_557_p2");
    sc_trace(mVcdFile, sel_tmp5_demorgan_fu_570_p2, "sel_tmp5_demorgan_fu_570_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_574_p2, "sel_tmp5_fu_574_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_580_p2, "sel_tmp6_fu_580_p2");
    sc_trace(mVcdFile, grp_fu_385_p2, "grp_fu_385_p2");
    sc_trace(mVcdFile, dist_matmul_4_fu_562_p3, "dist_matmul_4_fu_562_p3");
    sc_trace(mVcdFile, dist_matmul_5_fu_585_p3, "dist_matmul_5_fu_585_p3");
    sc_trace(mVcdFile, tmp_39_to_int_fu_604_p1, "tmp_39_to_int_fu_604_p1");
    sc_trace(mVcdFile, tmp_41_to_int_fu_622_p1, "tmp_41_to_int_fu_622_p1");
    sc_trace(mVcdFile, tmp_42_fu_608_p4, "tmp_42_fu_608_p4");
    sc_trace(mVcdFile, tmp_62_fu_618_p1, "tmp_62_fu_618_p1");
    sc_trace(mVcdFile, notrhs_fu_645_p2, "notrhs_fu_645_p2");
    sc_trace(mVcdFile, notlhs_fu_639_p2, "notlhs_fu_639_p2");
    sc_trace(mVcdFile, tmp_54_fu_625_p4, "tmp_54_fu_625_p4");
    sc_trace(mVcdFile, tmp_68_fu_635_p1, "tmp_68_fu_635_p1");
    sc_trace(mVcdFile, notrhs1_fu_663_p2, "notrhs1_fu_663_p2");
    sc_trace(mVcdFile, notlhs1_fu_657_p2, "notlhs1_fu_657_p2");
    sc_trace(mVcdFile, tmp_63_fu_651_p2, "tmp_63_fu_651_p2");
    sc_trace(mVcdFile, tmp_64_fu_669_p2, "tmp_64_fu_669_p2");
    sc_trace(mVcdFile, tmp_65_fu_675_p2, "tmp_65_fu_675_p2");
    sc_trace(mVcdFile, tmp_66_fu_411_p2, "tmp_66_fu_411_p2");
    sc_trace(mVcdFile, tmp_69_fu_750_p4, "tmp_69_fu_750_p4");
    sc_trace(mVcdFile, grp_fu_379_opcode, "grp_fu_379_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

sph_dec::~sph_dec() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dist_array_U;
    delete switch_point_U;
    delete U_U;
    delete predictive_controbkb_U47;
    delete predictive_controlbW_U48;
    delete predictive_controcud_U49;
    delete predictive_contromb6_U50;
    delete predictive_controeOg_U51;
    delete predictive_controncg_U52;
    delete predictive_controocq_U53;
}

void sph_dec::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sph_dec::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3EB0C6F7A0B5ED8D;
}

void sph_dec::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_5;
}

void sph_dec::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        dist_matmul_reg_306 = dist_matmul_3_fu_593_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        dist_matmul_reg_306 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_447_p2.read(), ap_const_lv1_1))) {
        i1_reg_284 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_57_fu_739_p2.read()))) {
        i1_reg_284 = i_reg_818.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ii_reg_295 = ii_1_reg_848.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ii_reg_295 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_s_fu_441_p2.read()))) {
        invdar_reg_250 = indvarinc_fu_430_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        invdar_reg_250 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_fu_681_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_45_fu_693_p2.read()))) {
        jj_reg_318 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        jj_reg_318 = jj_1_reg_944.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        kk_reg_355 = ap_const_lv4_B;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        kk_reg_355 = grp_fu_416_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_67_fu_681_p2.read()))) {
        level_3_ph_reg_329 = level_reg_272.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_fu_681_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_fu_693_p2.read()))) {
        level_3_ph_reg_329 = level_1_fu_699_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_reg_928.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_45_reg_932.read()))) {
        level_3_ph_reg_329 = ap_const_lv32_B;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        level_3_reg_343 = ap_phi_mux_level_3_ph_phi_fu_332_p6.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        level_3_reg_343 = ap_phi_mux_level_4_phi_fu_371_p4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_fu_760_p2.read()))) {
        level_4_reg_367 = level_3_reg_343.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_972.read()))) {
        level_4_reg_367 = level_5_cast_fu_771_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_447_p2.read(), ap_const_lv1_1))) {
        level_reg_272 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_57_fu_739_p2.read()))) {
        level_reg_272 = level_3_reg_343.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_441_p2.read()))) {
        ll_reg_261 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_447_p2.read(), ap_const_lv1_0))) {
        ll_reg_261 = ll_1_fu_453_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_710_p2.read()))) {
        p_0_fu_102 = reg_422.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_447_p2.read(), ap_const_lv1_1))) {
        p_0_fu_102 = roh.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dist_array_load_reg_907 = dist_array_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_818 = i_fu_474_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        icmp_reg_972 = icmp_fu_760_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ii_1_reg_848 = ii_1_fu_513_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        jj_1_reg_944 = jj_1_fu_716_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_760_p2.read()))) {
        level_2_reg_976 = grp_fu_416_p2.read();
        switch_point_addr_4_reg_981 =  (sc_lv<4>) (tmp_60_fu_766_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        reg_422 = grp_fu_379_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_468_p2.read(), ap_const_lv1_0))) {
        switch_point_addr_2_reg_830 =  (sc_lv<4>) (tmp_36_fu_480_p1.read());
        tmp_36_reg_823 = tmp_36_fu_480_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_57_fu_739_p2.read()))) {
        switch_point_addr_3_reg_967 =  (sc_lv<4>) (tmp_58_fu_745_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        switch_point_load_reg_835 = switch_point_q0.read();
        tmp_37_reg_840 = tmp_37_fu_497_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        tmp_38_reg_912 = grp_fu_393_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        tmp_41_reg_922 = grp_fu_405_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_507_p2.read()))) {
        tmp_43_reg_853 = tmp_43_fu_519_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_fu_681_p2.read()))) {
        tmp_45_reg_932 = tmp_45_fu_693_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_43_reg_853.read()))) {
        tmp_47_reg_880 = tmp_47_fu_540_p2.read();
        tmp_51_reg_892 = tmp_51_fu_546_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_710_p2.read()))) {
        tmp_55_reg_949 = tmp_55_fu_722_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        tmp_67_reg_928 = tmp_67_fu_681_p2.read();
    }
}

void sph_dec::thread_U_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        U_address0 =  (sc_lv<4>) (tmp_55_fu_722_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        U_address0 =  (sc_lv<4>) (tmp_46_fu_525_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        U_address0 =  (sc_lv<4>) (tmp_36_reg_823.read());
    } else {
        U_address0 = "XXXX";
    }
}

void sph_dec::thread_U_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        U_ce0 = ap_const_logic_1;
    } else {
        U_ce0 = ap_const_logic_0;
    }
}

void sph_dec::thread_U_opt_address0() {
    U_opt_address0 =  (sc_lv<4>) (tmp_55_reg_949.read());
}

void sph_dec::thread_U_opt_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        U_opt_ce0 = ap_const_logic_1;
    } else {
        U_opt_ce0 = ap_const_logic_0;
    }
}

void sph_dec::thread_U_opt_d0() {
    U_opt_d0 = grp_fu_397_p1.read();
}

void sph_dec::thread_U_opt_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        U_opt_we0 = ap_const_logic_1;
    } else {
        U_opt_we0 = ap_const_logic_0;
    }
}

void sph_dec::thread_U_unc_address0() {
    U_unc_address0 =  (sc_lv<4>) (tmp_36_reg_823.read());
}

void sph_dec::thread_U_unc_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        U_unc_ce0 = ap_const_logic_1;
    } else {
        U_unc_ce0 = ap_const_logic_0;
    }
}

void sph_dec::thread_U_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        U_we0 = ap_const_logic_1;
    } else {
        U_we0 = ap_const_logic_0;
    }
}

void sph_dec::thread_V_Gen_a_address0() {
    V_Gen_a_address0 =  (sc_lv<8>) (tmp_50_fu_535_p1.read());
}

void sph_dec::thread_V_Gen_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        V_Gen_a_ce0 = ap_const_logic_1;
    } else {
        V_Gen_a_ce0 = ap_const_logic_0;
    }
}

void sph_dec::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sph_dec::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sph_dec::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sph_dec::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sph_dec::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void sph_dec::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void sph_dec::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void sph_dec::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sph_dec::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void sph_dec::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void sph_dec::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void sph_dec::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void sph_dec::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void sph_dec::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void sph_dec::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void sph_dec::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void sph_dec::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void sph_dec::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sph_dec::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void sph_dec::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void sph_dec::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void sph_dec::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void sph_dec::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_468_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sph_dec::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sph_dec::thread_ap_phi_mux_level_3_ph_phi_fu_332_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_reg_928.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_45_reg_932.read()))) {
        ap_phi_mux_level_3_ph_phi_fu_332_p6 = ap_const_lv32_B;
    } else {
        ap_phi_mux_level_3_ph_phi_fu_332_p6 = level_3_ph_reg_329.read();
    }
}

void sph_dec::thread_ap_phi_mux_level_4_phi_fu_371_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_972.read()))) {
        ap_phi_mux_level_4_phi_fu_371_p4 = level_5_cast_fu_771_p1.read();
    } else {
        ap_phi_mux_level_4_phi_fu_371_p4 = level_4_reg_367.read();
    }
}

void sph_dec::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_468_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sph_dec::thread_dist_array_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        dist_array_address0 =  (sc_lv<4>) (tmp_48_fu_705_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        dist_array_address0 =  (sc_lv<4>) (tmp_36_reg_823.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        dist_array_address0 =  (sc_lv<4>) (tmp_fu_436_p1.read());
    } else {
        dist_array_address0 = "XXXX";
    }
}

void sph_dec::thread_dist_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        dist_array_ce0 = ap_const_logic_1;
    } else {
        dist_array_ce0 = ap_const_logic_0;
    }
}

void sph_dec::thread_dist_array_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        dist_array_d0 = reg_422.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        dist_array_d0 = ap_const_lv32_0;
    } else {
        dist_array_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sph_dec::thread_dist_array_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_fu_681_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_45_fu_693_p2.read())))) {
        dist_array_we0 = ap_const_logic_1;
    } else {
        dist_array_we0 = ap_const_logic_0;
    }
}

void sph_dec::thread_dist_matmul_3_fu_593_p3() {
    dist_matmul_3_fu_593_p3 = (!tmp_43_reg_853.read()[0].is_01())? sc_lv<32>(): ((tmp_43_reg_853.read()[0].to_bool())? dist_matmul_reg_306.read(): dist_matmul_5_fu_585_p3.read());
}

void sph_dec::thread_dist_matmul_4_fu_562_p3() {
    dist_matmul_4_fu_562_p3 = (!sel_tmp1_fu_557_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_fu_557_p2.read()[0].to_bool())? grp_fu_379_p2.read(): dist_matmul_reg_306.read());
}

void sph_dec::thread_dist_matmul_5_fu_585_p3() {
    dist_matmul_5_fu_585_p3 = (!sel_tmp6_fu_580_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp6_fu_580_p2.read()[0].to_bool())? grp_fu_385_p2.read(): dist_matmul_4_fu_562_p3.read());
}

void sph_dec::thread_exitcond1_fu_507_p2() {
    exitcond1_fu_507_p2 = (!ii_reg_295.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(ii_reg_295.read() == ap_const_lv4_C);
}

void sph_dec::thread_exitcond2_fu_468_p2() {
    exitcond2_fu_468_p2 = (!i1_reg_284.read().is_01() || !ap_const_lv6_23.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_284.read() == ap_const_lv6_23);
}

void sph_dec::thread_exitcond3_fu_447_p2() {
    exitcond3_fu_447_p2 = (!ll_reg_261.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(ll_reg_261.read() == ap_const_lv4_C);
}

void sph_dec::thread_exitcond_fu_710_p2() {
    exitcond_fu_710_p2 = (!jj_reg_318.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(jj_reg_318.read() == ap_const_lv4_C);
}

void sph_dec::thread_grp_fu_379_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_379_opcode = ap_const_lv2_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_43_reg_853.read())) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        grp_fu_379_opcode = ap_const_lv2_0;
    } else {
        grp_fu_379_opcode =  (sc_lv<2>) ("XX");
    }
}

void sph_dec::thread_grp_fu_379_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_379_p0 = tmp_38_reg_912.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_379_p0 = U_unc_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_379_p0 = dist_matmul_reg_306.read();
    } else {
        grp_fu_379_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sph_dec::thread_grp_fu_379_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_379_p1 = dist_array_load_reg_907.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_379_p1 = dist_matmul_reg_306.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_379_p1 = V_Gen_a_q0.read();
    } else {
        grp_fu_379_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sph_dec::thread_grp_fu_402_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_402_p0 = reg_422.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        grp_fu_402_p0 = p_0_fu_102.read();
    } else {
        grp_fu_402_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sph_dec::thread_grp_fu_416_p2() {
    grp_fu_416_p2 = (!kk_reg_355.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<4>(): (sc_biguint<4>(kk_reg_355.read()) + sc_bigint<4>(ap_const_lv4_F));
}

void sph_dec::thread_i_fu_474_p2() {
    i_fu_474_p2 = (!i1_reg_284.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i1_reg_284.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void sph_dec::thread_icmp_fu_760_p2() {
    icmp_fu_760_p2 = (!tmp_69_fu_750_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_69_fu_750_p4.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void sph_dec::thread_ii_1_fu_513_p2() {
    ii_1_fu_513_p2 = (!ii_reg_295.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ii_reg_295.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sph_dec::thread_ii_cast_fu_503_p1() {
    ii_cast_fu_503_p1 = esl_zext<32,4>(ii_reg_295.read());
}

void sph_dec::thread_indvarinc_fu_430_p2() {
    indvarinc_fu_430_p2 = (!invdar_reg_250.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(invdar_reg_250.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sph_dec::thread_jj_1_fu_716_p2() {
    jj_1_fu_716_p2 = (!jj_reg_318.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(jj_reg_318.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sph_dec::thread_level_1_fu_699_p2() {
    level_1_fu_699_p2 = (!level_reg_272.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(level_reg_272.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sph_dec::thread_level_5_cast_fu_771_p1() {
    level_5_cast_fu_771_p1 = esl_zext<32,4>(level_2_reg_976.read());
}

void sph_dec::thread_ll_1_fu_453_p2() {
    ll_1_fu_453_p2 = (!ll_reg_261.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ll_reg_261.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sph_dec::thread_notlhs1_fu_657_p2() {
    notlhs1_fu_657_p2 = (!tmp_54_fu_625_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_54_fu_625_p4.read() != ap_const_lv11_7FF);
}

void sph_dec::thread_notlhs_fu_639_p2() {
    notlhs_fu_639_p2 = (!tmp_42_fu_608_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_42_fu_608_p4.read() != ap_const_lv11_7FF);
}

void sph_dec::thread_notrhs1_fu_663_p2() {
    notrhs1_fu_663_p2 = (!tmp_68_fu_635_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_68_fu_635_p1.read() == ap_const_lv52_0);
}

void sph_dec::thread_notrhs_fu_645_p2() {
    notrhs_fu_645_p2 = (!tmp_62_fu_618_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_62_fu_618_p1.read() == ap_const_lv52_0);
}

void sph_dec::thread_sel_tmp1_fu_557_p2() {
    sel_tmp1_fu_557_p2 = (tmp_47_reg_880.read() & sel_tmp_fu_552_p2.read());
}

void sph_dec::thread_sel_tmp5_demorgan_fu_570_p2() {
    sel_tmp5_demorgan_fu_570_p2 = (tmp_43_reg_853.read() | tmp_47_reg_880.read());
}

void sph_dec::thread_sel_tmp5_fu_574_p2() {
    sel_tmp5_fu_574_p2 = (sel_tmp5_demorgan_fu_570_p2.read() ^ ap_const_lv1_1);
}

void sph_dec::thread_sel_tmp6_fu_580_p2() {
    sel_tmp6_fu_580_p2 = (tmp_51_reg_892.read() & sel_tmp5_fu_574_p2.read());
}

void sph_dec::thread_sel_tmp_fu_552_p2() {
    sel_tmp_fu_552_p2 = (tmp_43_reg_853.read() ^ ap_const_lv1_1);
}

void sph_dec::thread_switch_point_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        switch_point_address0 = switch_point_addr_3_reg_967.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        switch_point_address0 =  (sc_lv<4>) (tmp_58_fu_745_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()))) {
        switch_point_address0 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        switch_point_address0 = switch_point_addr_2_reg_830.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        switch_point_address0 =  (sc_lv<4>) (tmp_36_fu_480_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        switch_point_address0 =  (sc_lv<4>) (tmp_34_fu_459_p1.read());
    } else {
        switch_point_address0 = "XXXX";
    }
}

void sph_dec::thread_switch_point_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        switch_point_address1 = switch_point_addr_4_reg_981.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        switch_point_address1 =  (sc_lv<4>) (tmp_60_fu_766_p1.read());
    } else {
        switch_point_address1 = "XXXX";
    }
}

void sph_dec::thread_switch_point_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()))) {
        switch_point_ce0 = ap_const_logic_1;
    } else {
        switch_point_ce0 = ap_const_logic_0;
    }
}

void sph_dec::thread_switch_point_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()))) {
        switch_point_ce1 = ap_const_logic_1;
    } else {
        switch_point_ce1 = ap_const_logic_0;
    }
}

void sph_dec::thread_switch_point_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        switch_point_d0 = tmp_52_fu_732_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        switch_point_d0 = tmp_44_fu_687_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()))) {
        switch_point_d0 = ap_const_lv32_FFFFFFFF;
    } else {
        switch_point_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void sph_dec::thread_switch_point_d1() {
    switch_point_d1 = (!switch_point_q1.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(switch_point_q1.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sph_dec::thread_switch_point_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_fu_760_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond3_fu_447_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_reg_928.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_45_reg_932.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_67_fu_681_p2.read())))) {
        switch_point_we0 = ap_const_logic_1;
    } else {
        switch_point_we0 = ap_const_logic_0;
    }
}

void sph_dec::thread_switch_point_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_972.read()))) {
        switch_point_we1 = ap_const_logic_1;
    } else {
        switch_point_we1 = ap_const_logic_0;
    }
}

void sph_dec::thread_tmp_34_fu_459_p1() {
    tmp_34_fu_459_p1 = esl_zext<64,4>(ll_reg_261.read());
}

void sph_dec::thread_tmp_36_fu_480_p1() {
    tmp_36_fu_480_p1 = esl_sext<64,32>(level_reg_272.read());
}

void sph_dec::thread_tmp_37_fu_497_p2() {
    tmp_37_fu_497_p2 = (!tmp_53_fu_485_p2.read().is_01() || !tmp_59_fu_491_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_53_fu_485_p2.read()) - sc_biguint<32>(tmp_59_fu_491_p2.read()));
}

void sph_dec::thread_tmp_39_to_int_fu_604_p1() {
    tmp_39_to_int_fu_604_p1 = grp_fu_402_p1.read();
}

void sph_dec::thread_tmp_41_to_int_fu_622_p1() {
    tmp_41_to_int_fu_622_p1 = tmp_41_reg_922.read();
}

void sph_dec::thread_tmp_42_fu_608_p4() {
    tmp_42_fu_608_p4 = tmp_39_to_int_fu_604_p1.read().range(62, 52);
}

void sph_dec::thread_tmp_43_fu_519_p2() {
    tmp_43_fu_519_p2 = (!ii_cast_fu_503_p1.read().is_01() || !level_reg_272.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ii_cast_fu_503_p1.read()) > sc_bigint<32>(level_reg_272.read()));
}

void sph_dec::thread_tmp_44_fu_687_p2() {
    tmp_44_fu_687_p2 = (!switch_point_load_reg_835.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(switch_point_load_reg_835.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sph_dec::thread_tmp_45_fu_693_p2() {
    tmp_45_fu_693_p2 = (!level_reg_272.read().is_01() || !ap_const_lv32_B.is_01())? sc_lv<1>(): sc_lv<1>(level_reg_272.read() == ap_const_lv32_B);
}

void sph_dec::thread_tmp_46_fu_525_p1() {
    tmp_46_fu_525_p1 = esl_zext<64,4>(ii_reg_295.read());
}

void sph_dec::thread_tmp_47_fu_540_p2() {
    tmp_47_fu_540_p2 = (!U_q0.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(U_q0.read() == ap_const_lv32_1);
}

void sph_dec::thread_tmp_48_fu_705_p1() {
    tmp_48_fu_705_p1 = esl_sext<64,32>(level_1_fu_699_p2.read());
}

void sph_dec::thread_tmp_49_fu_530_p2() {
    tmp_49_fu_530_p2 = (!ii_cast_fu_503_p1.read().is_01() || !tmp_37_reg_840.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ii_cast_fu_503_p1.read()) + sc_biguint<32>(tmp_37_reg_840.read()));
}

void sph_dec::thread_tmp_50_fu_535_p1() {
    tmp_50_fu_535_p1 = esl_sext<64,32>(tmp_49_fu_530_p2.read());
}

void sph_dec::thread_tmp_51_fu_546_p2() {
    tmp_51_fu_546_p2 = (!U_q0.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<1>(): sc_lv<1>(U_q0.read() == ap_const_lv32_FFFFFFFF);
}

void sph_dec::thread_tmp_52_fu_732_p2() {
    tmp_52_fu_732_p2 = (!switch_point_q0.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(switch_point_q0.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sph_dec::thread_tmp_53_fu_485_p2() {
    tmp_53_fu_485_p2 = (!ap_const_lv32_4.is_01())? sc_lv<32>(): level_reg_272.read() << (unsigned short)ap_const_lv32_4.to_uint();
}

void sph_dec::thread_tmp_54_fu_625_p4() {
    tmp_54_fu_625_p4 = tmp_41_to_int_fu_622_p1.read().range(62, 52);
}

void sph_dec::thread_tmp_55_fu_722_p1() {
    tmp_55_fu_722_p1 = esl_zext<64,4>(jj_reg_318.read());
}

void sph_dec::thread_tmp_57_fu_739_p2() {
    tmp_57_fu_739_p2 = (!kk_reg_355.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(kk_reg_355.read() == ap_const_lv4_0);
}

void sph_dec::thread_tmp_58_fu_745_p1() {
    tmp_58_fu_745_p1 = esl_zext<64,4>(kk_reg_355.read());
}

void sph_dec::thread_tmp_59_fu_491_p2() {
    tmp_59_fu_491_p2 = (!ap_const_lv32_2.is_01())? sc_lv<32>(): level_reg_272.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void sph_dec::thread_tmp_60_fu_766_p1() {
    tmp_60_fu_766_p1 = esl_zext<64,4>(grp_fu_416_p2.read());
}

void sph_dec::thread_tmp_62_fu_618_p1() {
    tmp_62_fu_618_p1 = tmp_39_to_int_fu_604_p1.read().range(52-1, 0);
}

void sph_dec::thread_tmp_63_fu_651_p2() {
    tmp_63_fu_651_p2 = (notrhs_fu_645_p2.read() | notlhs_fu_639_p2.read());
}

void sph_dec::thread_tmp_64_fu_669_p2() {
    tmp_64_fu_669_p2 = (notrhs1_fu_663_p2.read() | notlhs1_fu_657_p2.read());
}

void sph_dec::thread_tmp_65_fu_675_p2() {
    tmp_65_fu_675_p2 = (tmp_63_fu_651_p2.read() & tmp_64_fu_669_p2.read());
}

void sph_dec::thread_tmp_67_fu_681_p2() {
    tmp_67_fu_681_p2 = (tmp_65_fu_675_p2.read() & tmp_66_fu_411_p2.read());
}

void sph_dec::thread_tmp_68_fu_635_p1() {
    tmp_68_fu_635_p1 = tmp_41_to_int_fu_622_p1.read().range(52-1, 0);
}

void sph_dec::thread_tmp_69_fu_750_p4() {
    tmp_69_fu_750_p4 = switch_point_q0.read().range(31, 1);
}

void sph_dec::thread_tmp_fu_436_p1() {
    tmp_fu_436_p1 = esl_zext<64,4>(invdar_reg_250.read());
}

void sph_dec::thread_tmp_s_fu_441_p2() {
    tmp_s_fu_441_p2 = (!invdar_reg_250.read().is_01() || !ap_const_lv4_B.is_01())? sc_lv<1>(): sc_lv<1>(invdar_reg_250.read() == ap_const_lv4_B);
}

void sph_dec::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_fu_441_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond3_fu_447_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_468_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_507_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_67_fu_681_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_45_fu_693_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state22;
            } else {
                ap_NS_fsm = ap_ST_fsm_state26;
            }
            break;
        case 2097152 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_710_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state26;
            } else {
                ap_NS_fsm = ap_ST_fsm_state23;
            }
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_57_fu_739_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state28;
            }
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<29>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

